In [1]:
import numpy as np
import pandas as pd

## Comparison UFuncs as Array Masks

Here is a brief review of what we've covered in the last lecture:

1. Seen how the comparison ufuncs (np.equal, np.less, np.greater, etc) generate boolean arrays that indicate whether a given element of an array meets (or doesn't meet) the condition of the function.

1. We then showed how you could pass these boolean areas to `np.sum`, `np.all`, and `np.any` to derive additional information on your data set.

1. Finally, we demonstrated how you could logically compare two boolean arrays with the **bitwise** operators to perform multistep data comparisons.

For the last segment of this tutorial, we are going to demonstrate using comparison functions to return the original items of the array that is being evaluated instead of a boolean array.

#### Array Masking
In the last lecture, we showed how you could select data from an array using index or slice notation. Here we will introduce another data selection technique called **masking**.

Basically, it looks a lot like slice notation. In case you've forgotten what that looks like, here is a reminder.

In [2]:
simple_int_array = np.array([5, 3, 4, 9, 8, 2, 1, 7, 6, 0])
simple_int_array

array([5, 3, 4, 9, 8, 2, 1, 7, 6, 0])

In [3]:
# Slice elements indexed 5, 6, 7 of our simple_int_array
simple_int_array[5:8]

array([2, 1, 7])

The difference with a mask is that instead of putting `[start:stop:step]` inside the brackets, you actually invoke a comparison function.

In [4]:
simple_int_array < 7

array([ True,  True,  True, False, False,  True,  True, False,  True,
        True])

In [5]:
# Let's return all the values of simple_int_array that are less than 7
# We will create a mask using comparison ufuncts and pass that back into the array

print(simple_int_array)
mask = simple_int_array < 7
print(mask)
simple_int_array[mask]

[5 3 4 9 8 2 1 7 6 0]
[ True  True  True False False  True  True False  True  True]


array([5, 3, 4, 2, 1, 6, 0])

In [6]:
# more common, is to accomplish this task inline
subset_array = simple_int_array[simple_int_array < 7]

array([5, 3, 4, 2, 1, 6, 0])

**This way of masking is very important and used a lot.** The above statement works the following way
1. The comparison UFunc inside the brackets is evaluated first. 
1. It returns a boolean array where the first 7 elements have `True` value, and the rest have `False`.
1. For each index of the boolean array with a `True` value, the corresponding index of the original array is returned.

In [2]:
# At this point you don't have to know the details of following data loading. 
# However, understand that it is loading the weights of all the athletes
nd_player_weights = np.array(pd.read_csv('./data/nd-football-2018-roster.csv')['Weight'])
nd_player_names = np.array(pd.read_csv('./data/nd-football-2018-roster.csv')['Name'])
nd_player_heights = np.array(pd.read_csv('./data/nd-football-2018-roster.csv')['Height'])

## Activity:

* Names of all players above 75 inches? 
* Names of all players above 220 lbs and below 250 lbs? 

**Hint**: You can use use boolean array created from one array as mask to another array

In [13]:
# create a mask using heights and weights, pass the mask into the names array

nd_player_names[nd_player_heights > 75]

# this is a 2 step process for players less than 75:
less_than_75_mask = nd_player_heights < 75
nd_player_names[less_than_75_mask]

# remember to use the () here:
nd_player_names[ (nd_player_weights > 220) & (nd_player_weights < 250) ]

array(['Jordan Genmark Heath', "Te'von Coney", 'Brandon Wimbush',
       'D.J. Morgan', 'Justin Ademilola', 'Asmar Bilal', 'Drue Tranquill',
       'Tommy Tremble', 'Ovie Oghoufo', 'Jack Lamb', 'Shayne Simon',
       'Keenan Sweeney', 'Drew White', 'Julian Okwara', 'Jamir Jones',
       'Jonathan Jones', 'Kofi Wardlow', 'Jack Henige*',
       'Brandon Hutson*', 'Devyn Spruell*', 'Bo Bauer', 'John Shannon',
       'Cody Benjamin*', 'Michael Vinson*', 'Miles Boykin', 'Nic Weishar',
       'Chase Claypool', 'Alizé Mack'], dtype=object)

## np.unique

Returns the sorted unique elements of an array. [More info](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html)

In [14]:
sample_array = np.array([1,2,2,1,2,3,2,23,2,1,3,2])
print(np.unique(sample_array))

[ 1  2  3 23]


# NumPy: Broadcasting

We look at how with UFuncs you can do arithmetic on a numpy array. We also looked at how you can do arithmetic on 2 numpy arrays. When it didn't work the error message mention `broadcasting`.

Broadcasting is how arrays talk to each other. We will again visit this idea later, but here is one explaination:

## Case 1

In [15]:
x = np.arange(3)
y = 5
print(x)
print(y)
print(x.shape)
print(x+y)

[0 1 2]
5
(3,)
[5 6 7]


## Case2

In [16]:
x = np.random.randint(10, size =((3,3)))
y = np.random.randint(10, size = 3)
print("x array")
print(x)
print("y array")
print(y)

print("Their shapes are respectively")
print(x.shape)
print(y.shape)

x array
[[9 1 3]
 [9 4 7]
 [0 8 9]]
y array
[7 8 9]
Their shapes are respectively
(3, 3)
(3,)


In [17]:
x - y

array([[ 2, -7, -6],
       [ 2, -4, -2],
       [-7,  0,  0]])

## Case 3

In [18]:
x = np.random.randint(10, size=(3,1))
y = np.random.randint(10, size = 3)
print("x  array")
print(x)
print("y array")
print(y)

print("Their shapes are respectively")
print(x.shape)
print(y.shape)

x  array
[[1]
 [4]
 [7]]
y array
[5 9 2]
Their shapes are respectively
(3, 1)
(3,)


In [19]:
x - y

array([[-4, -8, -1],
       [-1, -5,  2],
       [ 2, -2,  5]])

## Case 4

In [20]:
x = np.random.randint(10, size =((3,3)))
y = np.random.randint(10, size = (3,1))
print("x array")
print(x)
print("y array")
print(y)

print("Their shapes are respectively")
print(x.shape)
print(y.shape)
x + y

x array
[[9 3 3]
 [7 3 3]
 [0 3 1]]
y array
[[5]
 [6]
 [9]]
Their shapes are respectively
(3, 3)
(3, 1)


array([[14,  8,  8],
       [13,  9,  9],
       [ 9, 12, 10]])

# NumPy: Fancy Indexing

In [21]:
simple_array = np.array([10,20,30,40,50,60])
simple_array

array([10, 20, 30, 40, 50, 60])

In [22]:
simple_array[3]

40

In [23]:
simple_array[[5,0]]
# This is equivalent to np.array([simple_array[5], simple_array[0]])

array([60, 10])

In [24]:
np.array([simple_array[5], simple_array[0]])

array([60, 10])

## Application: np.argsort()

Returns the indices that would sort an array. [More Info](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html)



In [25]:
x = np.array(['d', 'a', 'b', 'x'])
np.argsort(x)

array([1, 2, 0, 3])

In [26]:
x[np.argsort(x)]

array(['a', 'b', 'd', 'x'], dtype='<U1')

# Detour to Dictionary

In [28]:
my_dictionary = dict()
print(my_dictionary)
my_dictionary = {}

{}


In [30]:
my_other_dictionary = {'key': 'value', 'key2': 'value 2'}
print(my_other_dictionary)

{'key': 'value', 'key2': 'value 2'}


In [31]:
my_dictionary['Jan'] = 1
my_dictionary['Feb'] = 2
my_dictionary['Mar'] = 3

my_dictionary

{'Jan': 1, 'Feb': 2, 'Mar': 3}

In [32]:
my_dictionary['Jan']

1

In [33]:
# You can update the dictionary through the key
my_dictionary['Jan'] = my_dictionary['Jan'] + 4

In [34]:
my_dictionary

{'Jan': 5, 'Feb': 2, 'Mar': 3}

In [35]:
# Accessing elements not in the dict
my_dictionary['Dec']

KeyError: 'Dec'

In [36]:
# To check if a key is in the list
'Dec' in my_dictionary

False

In [39]:
'Mar' in my_dictionary

True

## You can access the keys and values seperately

In [40]:
print(my_dictionary.keys())
print(my_dictionary.values())

list(my_dictionary.keys())

dict_keys(['Jan', 'Feb', 'Mar'])
dict_values([5, 2, 3])


['Jan', 'Feb', 'Mar']

In [41]:
np.array(list(my_dictionary.keys()))

array(['Jan', 'Feb', 'Mar'], dtype='<U3')

# Introduction to Pandas

<div class="alert alert-block alert-info">
<p> Source: Example datasets and discussion in this Jupyter Notebook was partly sourced from `Mike Dunn`, University of Notre Dame.  </p>
</div>

In [ ]:
import pandas as pd
pd.__version__

## `DataFrame` & `Series` Basics

### Basics on data loading

<div class="alert alert-block alert-info">
<h5>Know your current working directory</h5>

<p>`import os`</p>
<p>`os.getcwd()`</p>

</div>

In [42]:
import os
print(os.getcwd())

/Volumes/GoogleDrive/My Drive/ITAO/_current/notebooks


<div class="alert alert-block alert-danger">
<h5>Make sure the data is in the right place. </h5>
<p> </p>
<li> Open the above folder location, that was printed as an output of `os.getcwd()` command, using Windows (or Finder on Mac) file system</li>
<li> Make sure there is a folder named 'data' in the location you opened. If not create a folder</li>
<li> Copy the dowloaded data into the newly created 'data' folder </li>

</div>

In [43]:
print(os.listdir('./data/'))

['GoT_Character_Deaths.csv', 'Google_Stock_Price.csv', 'births.csv', 'college-loan-default-rates.csv', 'college-scorecard-data-scrubbed.csv', 'flight_sample.csv', 'flights_departures.csv', 'marketing.csv', 'nd-football-2018-roster.csv', 'pokedex.json', 'seattle_weather_2015_2016.csv', 'state-abbrevs.csv', 'state-areas.csv', 'state-population.csv', 'uscities_zip.csv', 'state-population-density.csv', 'bp_classific.csv', 'bank_campaign_small.csv']


When you specify './data/' in the above and below Python command, '.' means the current directory. 

In the following statement, the interpretation is that in the current directory as this Jupyter file, open the 'data' folder and look for 'nd-football-2018-roster.csv' file. 

In [3]:
athletes_data = pd.read_csv('./data/nd-football-2018-roster.csv')
type(athletes_data)

pandas.core.frame.DataFrame

<div class="alert alert-block alert-info">
The `type` function return the type of the object passed to it. Very handy.
</div> 

### `DataFrames` are made up of an `index` and one or more `Series`
Inside of every frame is an **`index`** and one or more **`Series`** objects.
Let's demonstrate this by looking at the first few elements of our `athletes_data` object.

In [48]:
#DataFrame athletes_data.head() provides the first few rows of the dataset

athletes_data.head(2)

Number                  Name Position  Height  Weight  Class  \
0       2       Dexter Williams       RB      71     215    Sr.   
1       2  Jordan Genmark Heath       LB      73     225  Soph.   

                           Hometown  
0           Orlando, FL/West Orange  
1  San Diego, CA/Cathedral Catholic

In [46]:
athletes_data.tail()

Number                    Name Position  Height  Weight  Class  \
111      94           Darnell Ewell       DT      75     330  Soph.   
112      95  Myron Tagovailoa-Amosa       DT      74     285  Soph.   
113      97      Micah Dew-Treadway       DT      76     300    Sr.   
114      98        Ja'Mion Franklin       DT      73     306    Fr.   
115      99           Jerry Tillery       DT      79     305    Sr.   

                             Hometown  
111           Norfolk, VA/Lake Taylor  
112             Ewa Beach, HI/Kapolei  
113                Bolingbrook, IL/HS  
114        Ridgely, MD/North Caroline  
115  Shreveport, LA/Evangel Christian

The bold numbers running down the left hand side are the **`index`** of the **`DataFrame`**.  The bold strings running across the top are the names of the nested **`DataSeries`** objects.

In [49]:
name_series = athletes_data['Name']
print(type(name_series))
name_series

<class 'pandas.core.series.Series'>


0             Dexter Williams
1        Jordan Genmark Heath
2                 Avery Davis
3            Houston Griffith
4                Te'von Coney
                ...          
111             Darnell Ewell
112    Myron Tagovailoa-Amosa
113        Micah Dew-Treadway
114          Ja'Mion Franklin
115             Jerry Tillery
Name: Name, Length: 116, dtype: object

<div class="alert alert-block alert-info">
<h5>Dictionary Like-Retrieval</h5>
<p>Did you see how I passed to the name of the **`DataSeries`** object that I wanted to the `athletes_data` frame? It was the same sort of syntax you'd use to retrieve a data element from a **`dict`**.</p>
<p>
As we continue to move along, we'll discover that **`DataFrame`** and **`dict`** types share many traits.
</p>
</div> 

### Every `Series` is made up of an index and a NumPy array
Now that we know every **`DataFrame`** is filled with **`Series`** objects, let's inspect `name_series` dig deeper into the data structures.

In [50]:
# Let's ask for the string representation of the object.
# You can ignore the slice notation at the end,
# I just don't want to display all the names.
name_series[0:10]

0         Dexter Williams
1    Jordan Genmark Heath
2             Avery Davis
3        Houston Griffith
4            Te'von Coney
5            Kevin Austin
6          Troy Pride Jr.
7          Tony Jones Jr.
8         Brandon Wimbush
9            Derrik Allen
Name: Name, dtype: object

So, as you can see, we've got two columns here.  
* The first column is the **`index`**.
* The second column, which holds the values of the series is nothing more than our good friend, the NumPy array.

You can retrieve the index and NumPy array separately from a series as follows:

In [51]:
# Get the Series index
name_series.index

RangeIndex(start=0, stop=116, step=1)

In [52]:
name_series.values

array(['Dexter Williams', 'Jordan Genmark Heath', 'Avery Davis',
       'Houston Griffith', "Te'von Coney", 'Kevin Austin',
       'Troy Pride Jr.', 'Tony Jones Jr.', 'Brandon Wimbush',
       'Derrik Allen', 'Jafar Armstrong', 'Donte Vaughn', 'Daelin Hayes',
       'Patrick Pelini*', 'Chris Finke', 'Alohi Gilman', 'Ian Book',
       'D.J. Brown', 'Lawrence Keys', 'Paul Moala', 'Devin Studstill',
       'J.D. Carney*', 'Phil Jurkovec', 'D.J. Morgan', 'Noah Boykin',
       'Isaiah Robertson', 'Nolan Henry*', 'Joe Wilkins Jr.',
       'Cameron Ekanayake*', 'Justin Yoon', 'Justin Ademilola',
       "C'Borius Flemister", 'Shaun Crawford', 'Jalen Elliott',
       'Asmar Bilal', 'Drue Tranquill', 'Tommy Tremble', 'Nick Coleman',
       'Braden Lenzy', 'John Mahoney*', 'Leo Albano*', 'Temitope Agoro*',
       'Julian Love', 'Arion Shinaver*', 'Nicco Fertitta', 'Ovie Oghoufo',
       'Matt Salerno', 'Jeremiah Owusu-Koramoah', 'Jake Rittman*',
       'Jack Lamb', 'Cole Capen*', 'Mick Assaf*', '

## Going a Bit Deeper
The essential difference between an NumPy **`ndarray`** and a Pandas **`Series`** object is their indexes.

**NumPy arrays have indexes as well, but they are implicit and always integers**. You can't access an array's **`index`** property directly like you can on a Pandas series object as we did above.

Furthermore, series objects are not limited to having integer based indexes. You could have indexes of strings, floats, booleans, dates, etc. 

In [53]:
# Create a `DataSeries` object from a dictionary
# This results in a string based index.

sample_dict = {
    'R':'Not as cool. ;-(',
    'Python': 'Best Language Ever!',
    'C': 'Fundamental language',
    'Julia': 'A New language for Data Science'
    }

simple_series = pd.Series(sample_dict)
print(simple_series.index)
print(simple_series.values)

Index(['R', 'Python', 'C', 'Julia'], dtype='object')
['Not as cool. ;-(' 'Best Language Ever!' 'Fundamental language'
 'A New language for Data Science']


In [54]:
simple_series

R                        Not as cool. ;-(
Python                Best Language Ever!
C                    Fundamental language
Julia     A New language for Data Science
dtype: object

In [55]:
simple_series['Python']

'Best Language Ever!'

In [56]:
simple_series['R':'Python']

R            Not as cool. ;-(
Python    Best Language Ever!
dtype: object

When we loaded our `athletes_data` frame from the CSV file, it generated an integer based index, which is the default behavior.

But we could change that.  For instance, we could make the institution names the index values:

In [57]:
athletes_data.head()

Number                  Name Position  Height  Weight  Class  \
0       2       Dexter Williams       RB      71     215    Sr.   
1       2  Jordan Genmark Heath       LB      73     225  Soph.   
2       3           Avery Davis       QB      71     204  Soph.   
3       3      Houston Griffith        S      72     205    Fr.   
4       4          Te'von Coney       LB      73     240    Sr.   

                           Hometown  
0           Orlando, FL/West Orange  
1  San Diego, CA/Cathedral Catholic  
2                 Cedar Hill, TX/HS  
3      Chicago, IL/IMG Academy (FL)  
4         Palm Beach Gardens, FL/HS

In [58]:
athletes_data.index = athletes_data['Name']

athletes_data.head()

Number                  Name Position  Height  Weight  \
Name                                                                          
Dexter Williams            2       Dexter Williams       RB      71     215   
Jordan Genmark Heath       2  Jordan Genmark Heath       LB      73     225   
Avery Davis                3           Avery Davis       QB      71     204   
Houston Griffith           3      Houston Griffith        S      72     205   
Te'von Coney               4          Te'von Coney       LB      73     240   

                      Class                          Hometown  
Name                                                           
Dexter Williams         Sr.           Orlando, FL/West Orange  
Jordan Genmark Heath  Soph.  San Diego, CA/Cathedral Catholic  
Avery Davis           Soph.                 Cedar Hill, TX/HS  
Houston Griffith        Fr.      Chicago, IL/IMG Academy (FL)  
Te'von Coney            Sr.         Palm Beach Gardens, FL/HS

In [59]:
athletes_data2 = pd.read_csv('./data/nd-football-2018-roster.csv')
athletes_data2.set_index('Name', inplace=True)
athletes_data2.head()

Number Position  Height  Weight  Class  \
Name                                                           
Dexter Williams            2       RB      71     215    Sr.   
Jordan Genmark Heath       2       LB      73     225  Soph.   
Avery Davis                3       QB      71     204  Soph.   
Houston Griffith           3        S      72     205    Fr.   
Te'von Coney               4       LB      73     240    Sr.   

                                              Hometown  
Name                                                    
Dexter Williams                Orlando, FL/West Orange  
Jordan Genmark Heath  San Diego, CA/Cathedral Catholic  
Avery Davis                          Cedar Hill, TX/HS  
Houston Griffith          Chicago, IL/IMG Academy (FL)  
Te'von Coney                 Palm Beach Gardens, FL/HS

# Data Indexing and Selection

You'll find that many of the same techniques that we used with NumPy arrays will also be available for these objects. In addition, they add some additional functionality that will be very familiar to anyone who has experience with Python dictionaries.

In [60]:
college_scorecard = pd.read_csv(
    './data/college-scorecard-data-scrubbed.csv')
college_scorecard.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 8: invalid continuation byte

### Encoding

Text files are encoded in different formats when they are written. To read them, you must decode them with the same standard or you'll have a problem.

For example, our `college-scorecard-data-scrubbed.csv` file was encoded using `latin-1`, but the default setting for Pandas in Python 3 is `utf-8` so we will get an error if we try to read the file without specify the correct encoding like so:

In [61]:
college_scorecard = pd.read_csv(
    './data/college-scorecard-data-scrubbed.csv', 
    encoding='latin-1')
college_scorecard.head()

UNITID    OPEID  OPEID6                        institution_name       city  \
0  102580   884300    8843                    Alaska Bible College     Palmer   
1  103501  2541000   25410                   Alaska Career College  Anchorage   
2  442523  4138600   41386                Alaska Christian College   Soldotna   
3  102669   106100    1061               Alaska Pacific University  Anchorage   
4  102711  3160300   31603  AVTEC-Alaska's Institute of Technology     Seward   

  state                          url  predominant_degree_code  \
0    AK             www.akbible.edu/                        3   
1    AK  www.alaskacareercollege.edu                        1   
2    AK             www.alaskacc.edu                        1   
3    AK        www.alaskapacific.edu                        3   
4    AK               www.avtec.edu/                        1   

  predominant_degree_desc  institutional_owner_code  ...  \
0               Bachelors                         2  ...   
1             Certificate                         3  ...   
2             Certificate                         2  ...   
3               Bachelors                         2  ...   
4             Certificate                         1  ...   

  pell_grant_receipents  full_time_retention_rate_4_year  \
0                0.3571                           0.3333   
1                0.7078                              NaN   
2                0.8868                              NaN   
3                0.3152                           0.7742   
4                0.0737                              NaN   

   full_time_retention_rate_less_than_4_year  \
0                                        NaN   
1                                     0.7941   
2                                     0.4737   
3                                        NaN   
4                                     1.0000   

   part_time_rentention_rate_4_year  \
0                               NaN   
1                               NaN   
2                               NaN   
3                               1.0   
4                               NaN   

   part_time_rentention_rate_less_than_4_year students_with_federal_loans  \
0                                         NaN                      0.2857   
1                                         NaN                      0.7860   
2                                         1.0                      0.6792   
3                                         NaN                      0.5297   
4                                         1.0                      0.0664   

   median_student_earnings  median_student_debt  \
0                      NaN    PrivacySuppressed   
1                    28700                 8994   
2                      NaN    PrivacySuppressed   
3                    47000                23250   
4                    33500    PrivacySuppressed   

   less_than_4_year_school_completion_rate  4_year_school_completion_rate  
0                                      NaN                            NaN  
1                              0.707589494                            NaN  
2                                        0                            NaN  
3                                      NaN                    0.514833663  
4                              0.846055789                            NaN  

[5 rows x 63 columns]

In [4]:
college_scorecard = pd.read_csv(
    './data/college-scorecard-data-scrubbed.csv', 
    encoding='latin-1', 
    index_col='institution_name')
college_scorecard.head()

UNITID    OPEID  OPEID6       city  \
institution_name                                                             
Alaska Bible College                    102580   884300    8843     Palmer   
Alaska Career College                   103501  2541000   25410  Anchorage   
Alaska Christian College                442523  4138600   41386   Soldotna   
Alaska Pacific University               102669   106100    1061  Anchorage   
AVTEC-Alaska's Institute of Technology  102711  3160300   31603     Seward   

                                       state                          url  \
institution_name                                                            
Alaska Bible College                      AK             www.akbible.edu/   
Alaska Career College                     AK  www.alaskacareercollege.edu   
Alaska Christian College                  AK             www.alaskacc.edu   
Alaska Pacific University                 AK        www.alaskapacific.edu   
AVTEC-Alaska's Institute of Technology    AK               www.avtec.edu/   

                                        predominant_degree_code  \
institution_name                                                  
Alaska Bible College                                          3   
Alaska Career College                                         1   
Alaska Christian College                                      1   
Alaska Pacific University                                     3   
AVTEC-Alaska's Institute of Technology                        1   

                                       predominant_degree_desc  \
institution_name                                                 
Alaska Bible College                                 Bachelors   
Alaska Career College                              Certificate   
Alaska Christian College                           Certificate   
Alaska Pacific University                            Bachelors   
AVTEC-Alaska's Institute of Technology             Certificate   

                                        institutional_owner_code  \
institution_name                                                   
Alaska Bible College                                           2   
Alaska Career College                                          3   
Alaska Christian College                                       2   
Alaska Pacific University                                      2   
AVTEC-Alaska's Institute of Technology                         1   

                                       institutional_owner_desc  ...  \
institution_name                                                 ...   
Alaska Bible College                           PrivateNonProfit  ...   
Alaska Career College                          PrivateForProfit  ...   
Alaska Christian College                       PrivateNonProfit  ...   
Alaska Pacific University                      PrivateNonProfit  ...   
AVTEC-Alaska's Institute of Technology                   Public  ...   

                                        pell_grant_receipents  \
institution_name                                                
Alaska Bible College                                   0.3571   
Alaska Career College                                  0.7078   
Alaska Christian College                               0.8868   
Alaska Pacific University                              0.3152   
AVTEC-Alaska's Institute of Technology                 0.0737   

                                        full_time_retention_rate_4_year  \
institution_name                                                          
Alaska Bible College                                             0.3333   
Alaska Career College                                               NaN   
Alaska Christian College                                            NaN   
Alaska Pacific University                                        0.7742   
AVTEC-Alaska's Institute of Technology                              NaN   

                                        full_time_retent

**NOTE**: In the last read_csv, we are using `index_col` keyword argument to provide the column we want to use as an index. This is a common way of loading CSV when we want a specific column to be an index. 

## Selecting Data from `Series` Objects

Let's start by grabbing the `url` series object out of our data frame:

In [63]:
url_series = college_scorecard['url']
url_series.head()

institution_name
Alaska Bible College                                 www.akbible.edu/
Alaska Career College                     www.alaskacareercollege.edu
Alaska Christian College                             www.alaskacc.edu
Alaska Pacific University                       www.alaskapacific.edu
AVTEC-Alaska's Institute of Technology                 www.avtec.edu/
Name: url, dtype: object

As a reminder, a `Series` object is comprised of an explicit index and the values. **Notice here that our `Series` object inherit the 'institution_name' column values as the index from the `DataFrame`.**

### Dictionary Like Features

Several of the methods available on Python **`dict`** objects are also available on `Series` objects. The reason that this is possible is because Pandas maintains a mapping relationship between the explicit index elements and the Series values - just like standard Python does between the keys & values of a dictionary.  

#### Membership Testing with `in`
You can determine if a given **index** exists in a `Series` using the `in` keyword:


In [64]:
'University of Notre Dame' in url_series

True

#### Value Retrieval via Index "Key"
You can retrieve a value from the `Series` by passing it the index "key" you are interest in.b

In [65]:
url_series['University of Notre Dame']

'www.nd.edu'

In [66]:
url_series['Carnegie Mellon University']

'www.cmu.edu/'

### Array Like Features
Now we will explore some of the array like features of `Series` objects. Most of this will be familiar given what you already know about NumPy arrays, so we will move quickly.

#### Slicing with Explicit Indexes & Implicit Indexes
Slicing is pretty straight forward with NumPy arrays because of their implicit integer based indexes. It gets a little bit more complicated with `Series` objects because the explicit index isn't necessarily integer based.

Just like normal slice, you can specify two elements that you want to be the start/end of what is returned. The difference here is that you can specify the actual index element names/keys instead of numbers.

Here will we ask for all the listings from Stanford to Notre Dame.

In [67]:
url_series['Stanford University':'University of Notre Dame']

institution_name
Stanford University                                         www.stanford.edu/
Starr King School for the Ministry                               www.sksm.edu
SUM Bible College and Theological Seminary                        www.sum.edu
Summit College                                          www.summitcollege.edu
Sutter Beauty College                                 sutterbeautycollege.com
                                                               ...           
Trine University                                                www.trine.edu
Trine University-Regional/Non-Traditional Campuses              www.trine.edu
University of Evansville                                  www.evansville.edu/
University of Indianapolis                                          uindy.edu
University of Notre Dame                                           www.nd.edu
Name: url, Length: 1530, dtype: object

<div class="alert alert-block alert-info">
<p>
It is important to note that the reverse request, `url_series['University of Notre Dame': 'Stanford University']` would have yielded no results.
</p>
<p>
This is because 'University of Notre Dame' appears after 'Stanford' in the CSV file. Remember that technically, the first item in a slice notation is the 'start' and the second is the 'end'. It is important that you have them in the right order.
</p>
</div> 

<div class="alert alert-block alert-danger">
<h5>Warning: Important Distinction</h5>
<p>
In a NumPy array slice (or when using an implicit index), the 'end' value of the slice notation is not included in the return slice.
</p>
<p>
Strangely, when using a slice with an explicit index - the end value is included. Be careful about this as you could end up with an extra record in your slices that you don't want.
</p>
</div> 

##### The Implicit Index Lurking in the Shadows

While it is true that every `Series` object has an explicit index - it is also true that there is also an implicit index that is always available. Because of this, you can continue to use "normal" slice notations on `Series` objects with non-integer based explicit indexes.

Here are a couple of examples.

In [68]:
# Using "normal" slice notations on our `url_series`
# First ten elements
url_series[0:10]

institution_name
Alaska Bible College                                 www.akbible.edu/
Alaska Career College                     www.alaskacareercollege.edu
Alaska Christian College                             www.alaskacc.edu
Alaska Pacific University                       www.alaskapacific.edu
AVTEC-Alaska's Institute of Technology                 www.avtec.edu/
Charter College-Anchorage                      www.chartercollege.edu
Ilisagvik College                                   www.ilisagvik.edu
University of Alaska Anchorage                     www.uaa.alaska.edu
University of Alaska Fairbanks                            www.uaf.edu
University of Alaska Southeast                     www.uas.alaska.edu
Name: url, dtype: object

<div class="alert alert-block alert-danger">
<h5>Important Warning! Implicit vs. Explicit indexing</h5>
<p>
A confusing situation arises when you have a `Series` with an explicit integer index that doesn't start with 0 and increment 1 for each element.
</p>

<p>
Slice notations get convoluted in this case and you have to use some ** special attributes (.loc, .iloc, .ix) that are discussed in your textbook on page 109-110** to keep things straight. 
</p>
</div> 

#### Series Masking
You can do masking on `Series` objects in the same way you did so with NumPy Arrays. Review the Jupyter Notebook for Sept 19th for more information on masking using NumPy

Here a couple of examples:

In [6]:
# Let's get a new Series object with numeric data on SAT average scores.
sat_average_series = college_scorecard['sat_average']

In [70]:
sat_average_series.head()

institution_name
Alaska Bible College                         NaN
Alaska Career College                        NaN
Alaska Christian College                     NaN
Alaska Pacific University                 1054.0
AVTEC-Alaska's Institute of Technology       NaN
Name: sat_average, dtype: float64

In [71]:
sat_average_series > 1300

institution_name
Alaska Bible College                      False
Alaska Career College                     False
Alaska Christian College                  False
Alaska Pacific University                 False
AVTEC-Alaska's Institute of Technology    False
                                          ...  
Northwest College                         False
Sheridan College                          False
University of Wyoming                     False
Western Wyoming Community College         False
Wyotech-Laramie                           False
Name: sat_average, Length: 7282, dtype: bool

In [72]:
# Return schools with SAT averages over 1200
sat_average_series[sat_average_series > 1300]

institution_name
California Institute of Technology    1545.0
Claremont McKenna College             1419.0
Harvey Mudd College                   1500.0
Pomona College                        1454.0
Santa Clara University                1309.0
                                       ...  
University of Richmond                1337.0
University of Virginia-Main Campus    1357.0
Washington and Lee University         1395.0
Middlebury College                    1379.0
Whitman College                       1323.0
Name: sat_average, Length: 82, dtype: float64

## Activity:

1. What schools have averages between 1400 & 1500
1. Is University of Notre Dame one of the schools? 
1. How about 'Harvard University'? 
1. If not, what is Harvards SAT average?


In [83]:
good_averages = sat_average_series[ (sat_average_series > 1300) & (sat_average_series < 1500) ]
"University of Notre Dame" in good_averages
"University of Michigan- Ann Arbor" in good_averages
"Harvard University" in good_averages
good_averages

institution_name
Claremont McKenna College             1419.0
Pomona College                        1454.0
Santa Clara University                1309.0
Scripps College                       1360.0
Stanford University                   1465.0
                                       ...  
University of Richmond                1337.0
University of Virginia-Main Campus    1357.0
Washington and Lee University         1395.0
Middlebury College                    1379.0
Whitman College                       1323.0
Name: sat_average, Length: 77, dtype: float64

## Selecting Data from `DataFrame` Objects

Similiarly to what we found with `Series` objects. You can interact with `DataFrame` objects in ways that sometimes resemble a dictionary and other times a NumPy array.

### Dictionary Like Features


In [43]:
college_scorecard.head()

UNITID    OPEID  OPEID6       city  \
institution_name                                                             
Alaska Bible College                    102580   884300    8843     Palmer   
Alaska Career College                   103501  2541000   25410  Anchorage   
Alaska Christian College                442523  4138600   41386   Soldotna   
Alaska Pacific University               102669   106100    1061  Anchorage   
AVTEC-Alaska's Institute of Technology  102711  3160300   31603     Seward   

                                       state                          url  \
institution_name                                                            
Alaska Bible College                      AK             www.akbible.edu/   
Alaska Career College                     AK  www.alaskacareercollege.edu   
Alaska Christian College                  AK             www.alaskacc.edu   
Alaska Pacific University                 AK        www.alaskapacific.edu   
AVTEC-Alaska's Institute of Technology    AK               www.avtec.edu/   

                                        predominant_degree_code  \
institution_name                                                  
Alaska Bible College                                          3   
Alaska Career College                                         1   
Alaska Christian College                                      1   
Alaska Pacific University                                     3   
AVTEC-Alaska's Institute of Technology                        1   

                                       predominant_degree_desc  \
institution_name                                                 
Alaska Bible College                                 Bachelors   
Alaska Career College                              Certificate   
Alaska Christian College                           Certificate   
Alaska Pacific University                            Bachelors   
AVTEC-Alaska's Institute of Technology             Certificate   

                                        institutional_owner_code  \
institution_name                                                   
Alaska Bible College                                           2   
Alaska Career College                                          3   
Alaska Christian College                                       2   
Alaska Pacific University                                      2   
AVTEC-Alaska's Institute of Technology                         1   

                                       institutional_owner_desc  ...  \
institution_name                                                 ...   
Alaska Bible College                           PrivateNonProfit  ...   
Alaska Career College                          PrivateForProfit  ...   
Alaska Christian College                       PrivateNonProfit  ...   
Alaska Pacific University                      PrivateNonProfit  ...   
AVTEC-Alaska's Institute of Technology                   Public  ...   

                                        pell_grant_receipents  \
institution_name                                                
Alaska Bible College                                   0.3571   
Alaska Career College                                  0.7078   
Alaska Christian College                               0.8868   
Alaska Pacific University                              0.3152   
AVTEC-Alaska's Institute of Technology                 0.0737   

                                        full_time_retention_rate_4_year  \
institution_name                                                          
Alaska Bible College                                             0.3333   
Alaska Career College                                               NaN   
Alaska Christian College                                            NaN   
Alaska Pacific University                                        0.7742   
AVTEC-Alaska's Institute of Technology                              NaN   

                                        full_time_retent

In [45]:
# You can retrieve an individual Series from a DataFrame
# by passing the Series name/key to the DataFrame
college_scorecard['religious_affiliation_desc'][:10]

institution_name
Alaska Bible College                                            Undenominational
Alaska Career College                                             Not applicable
Alaska Christian College                  Evangelical Covenant Church of America
Alaska Pacific University                                       United Methodist
AVTEC-Alaska's Institute of Technology                            Not applicable
Charter College-Anchorage                                         Not applicable
Ilisagvik College                                                 Not applicable
University of Alaska Anchorage                                    Not applicable
University of Alaska Fairbanks                                    Not applicable
University of Alaska Southeast                                    Not applicable
Name: religious_affiliation_desc, dtype: object

In [46]:
# Test for the existence of a given column/Series in a DataFrame
'city' in college_scorecard

True

In [47]:
college_scorecard['City']


KeyError: 'City'

<div class="alert alert-block alert-warning">
<p> Note the distiction with `in` operator on a `Series` and on a `DataFrame`. When you use it on a `Series` it checks if it is present in the index. Whereas for a `DataFrame`, it check if it is present in the columns
<div>

### Array Like Features

#### Slicing (Explicit Index)
Slicing affects affects rows, not columns in a `DataFrame`. In other words, you can slice based on the index values, but not the column values. Let's get a slice of all rows from 'Alaska Bible College' to 'Alabama State University':

In [48]:
college_scorecard['Alaska Bible College': 'Alabama State University']

UNITID    OPEID  OPEID6         city  \
institution_name                                                                
Alaska Bible College                     102580   884300    8843       Palmer   
Alaska Career College                    103501  2541000   25410    Anchorage   
Alaska Christian College                 442523  4138600   41386     Soldotna   
Alaska Pacific University                102669   106100    1061    Anchorage   
AVTEC-Alaska's Institute of Technology   102711  3160300   31603       Seward   
Charter College-Anchorage                102845  2576900   25769    Anchorage   
Ilisagvik College                        434584  3461300   34613       Barrow   
University of Alaska Anchorage           102553  1146200   11462    Anchorage   
University of Alaska Fairbanks           102614   106300    1063    Fairbanks   
University of Alaska Southeast           102632   106500    1065       Juneau   
Alabama A & M University                 100654   100200    1002       Normal   
Alabama College of Osteopathic Medicine  483975  4226700   42267       Dothan   
Alabama Southern Community College       101949   103400    1034  Monroeville   
Alabama State College of Barber Styling  371034  3032500   30325   Gardendale   
Alabama State University                 100724   100500    1005   Montgomery   

                                        state                          url  \
institution_name                                                             
Alaska Bible College                       AK             www.akbible.edu/   
Alaska Career College                      AK  www.alaskacareercollege.edu   
Alaska Christian College                   AK             www.alaskacc.edu   
Alaska Pacific University                  AK        www.alaskapacific.edu   
AVTEC-Alaska's Institute of Technology     AK               www.avtec.edu/   
Charter College-Anchorage                  AK       www.chartercollege.edu   
Ilisagvik College                          AK            www.ilisagvik.edu   
University of Alaska Anchorage             AK           www.uaa.alaska.edu   
University of Alaska Fairbanks             AK                  www.uaf.edu   
University of Alaska Southeast             AK           www.uas.alaska.edu   
Alabama A & M University                   AL                www.aamu.edu/   
Alabama College of Osteopathic Medicine    AL             www.acomedu.org/   
Alabama Southern Community College         AL                 www.ascc.edu   
Alabama State College of Barber Styling    AL                www.ascbs.edu   
Alabama State University                   AL                www.alasu.edu   

                                         predominant_degree_code  \
institution_name                                                   
Alaska Bible College                                           3   
Alaska Career College                                          1   
Alaska Christian College                                       1   
Alaska Pacific University                                      3   
AVTEC-Alaska's Institute of Technology                         1   
Charter College-Anchorage                                      1   
Ilisagvik College                                              1   
University of Alaska Anchorage                                 3   
University of Alaska Fairbanks                                 3   
University of Alaska Southeast                                 1   
Alabama A & M University                                       3   
Alabama College of Osteopathic Medicine                        4   
Alabama Southern Community College                             2   
Alabama State College of Barber Styling                        1   
Alabama State University                                       3   

                                        predominant_degree_desc  \
institution_name                                                  
Alaska Bible College                         

<div class="alert alert-block alert-info">
<p>
You can however use the `iloc`, and `loc` methods to slice based on columns.  **You can look into this on pages 113-114 of your textbook if you are interested.**</p>
</div> 

#### Slicing (implicit index)
You can also rely on the implicit integer index of the `DataFrame` (yes, it has one too) to retrieve rows by the numeric index.

**Just remember, the 'end' value of the slice is not included when using the implicit index.**

In [49]:
college_scorecard[0:5]

UNITID    OPEID  OPEID6       city  \
institution_name                                                             
Alaska Bible College                    102580   884300    8843     Palmer   
Alaska Career College                   103501  2541000   25410  Anchorage   
Alaska Christian College                442523  4138600   41386   Soldotna   
Alaska Pacific University               102669   106100    1061  Anchorage   
AVTEC-Alaska's Institute of Technology  102711  3160300   31603     Seward   

                                       state                          url  \
institution_name                                                            
Alaska Bible College                      AK             www.akbible.edu/   
Alaska Career College                     AK  www.alaskacareercollege.edu   
Alaska Christian College                  AK             www.alaskacc.edu   
Alaska Pacific University                 AK        www.alaskapacific.edu   
AVTEC-Alaska's Institute of Technology    AK               www.avtec.edu/   

                                        predominant_degree_code  \
institution_name                                                  
Alaska Bible College                                          3   
Alaska Career College                                         1   
Alaska Christian College                                      1   
Alaska Pacific University                                     3   
AVTEC-Alaska's Institute of Technology                        1   

                                       predominant_degree_desc  \
institution_name                                                 
Alaska Bible College                                 Bachelors   
Alaska Career College                              Certificate   
Alaska Christian College                           Certificate   
Alaska Pacific University                            Bachelors   
AVTEC-Alaska's Institute of Technology             Certificate   

                                        institutional_owner_code  \
institution_name                                                   
Alaska Bible College                                           2   
Alaska Career College                                          3   
Alaska Christian College                                       2   
Alaska Pacific University                                      2   
AVTEC-Alaska's Institute of Technology                         1   

                                       institutional_owner_desc  ...  \
institution_name                                                 ...   
Alaska Bible College                           PrivateNonProfit  ...   
Alaska Career College                          PrivateForProfit  ...   
Alaska Christian College                       PrivateNonProfit  ...   
Alaska Pacific University                      PrivateNonProfit  ...   
AVTEC-Alaska's Institute of Technology                   Public  ...   

                                        pell_grant_receipents  \
institution_name                                                
Alaska Bible College                                   0.3571   
Alaska Career College                                  0.7078   
Alaska Christian College                               0.8868   
Alaska Pacific University                              0.3152   
AVTEC-Alaska's Institute of Technology                 0.0737   

                                        full_time_retention_rate_4_year  \
institution_name                                                          
Alaska Bible College                                             0.3333   
Alaska Career College                                               NaN   
Alaska Christian College                                            NaN   
Alaska Pacific University                                        0.7742   
AVTEC-Alaska's Institute of Technology                              NaN   

                                        full_time_retent

#### Masking

Masking operations likewise return rows from a `DataFrame`, but the **criteria of the masks will be a comparison on one of the columns/Series**. This is somewhat confusing sounding, so let's just demonstrate:

In [50]:
# Return all rows where the 'state' Series has a value of 'AK'
college_scorecard[ college_scorecard['state'] == 'AK' ]

UNITID    OPEID  OPEID6       city  \
institution_name                                                             
Alaska Bible College                    102580   884300    8843     Palmer   
Alaska Career College                   103501  2541000   25410  Anchorage   
Alaska Christian College                442523  4138600   41386   Soldotna   
Alaska Pacific University               102669   106100    1061  Anchorage   
AVTEC-Alaska's Institute of Technology  102711  3160300   31603     Seward   
Charter College-Anchorage               102845  2576900   25769  Anchorage   
Ilisagvik College                       434584  3461300   34613     Barrow   
University of Alaska Anchorage          102553  1146200   11462  Anchorage   
University of Alaska Fairbanks          102614   106300    1063  Fairbanks   
University of Alaska Southeast          102632   106500    1065     Juneau   

                                       state                          url  \
institution_name                                                            
Alaska Bible College                      AK             www.akbible.edu/   
Alaska Career College                     AK  www.alaskacareercollege.edu   
Alaska Christian College                  AK             www.alaskacc.edu   
Alaska Pacific University                 AK        www.alaskapacific.edu   
AVTEC-Alaska's Institute of Technology    AK               www.avtec.edu/   
Charter College-Anchorage                 AK       www.chartercollege.edu   
Ilisagvik College                         AK            www.ilisagvik.edu   
University of Alaska Anchorage            AK           www.uaa.alaska.edu   
University of Alaska Fairbanks            AK                  www.uaf.edu   
University of Alaska Southeast            AK           www.uas.alaska.edu   

                                        predominant_degree_code  \
institution_name                                                  
Alaska Bible College                                          3   
Alaska Career College                                         1   
Alaska Christian College                                      1   
Alaska Pacific University                                     3   
AVTEC-Alaska's Institute of Technology                        1   
Charter College-Anchorage                                     1   
Ilisagvik College                                             1   
University of Alaska Anchorage                                3   
University of Alaska Fairbanks                                3   
University of Alaska Southeast                                1   

                                       predominant_degree_desc  \
institution_name                                                 
Alaska Bible College                                 Bachelors   
Alaska Career College                              Certificate   
Alaska Christian College                           Certificate   
Alaska Pacific University                            Bachelors   
AVTEC-Alaska's Institute of Technology             Certificate   
Charter College-Anchorage                          Certificate   
Ilisagvik College                                  Certificate   
University of Alaska Anchorage                       Bachelors   
University of Alaska Fairbanks                       Bachelors   
University of Alaska Southeast                     Certificate   

                                        institutional_owner_code  \
institution_name                                                   
Alaska Bible College                                           2   
Alaska Career College                                          3   
Alaska Christian College                                       2   
Alaska Pacific University                                      2   
AVTEC-Alaska's Institute of Technology                         1   
Charter College-Anchorage                                      3   
Ilisagvik College                   

In [51]:
# Which colleges in IN offer Bachelors degrees?
# Again, notice the parathesis here
college_scorecard[ (college_scorecard['state'] == 'IN') & (college_scorecard['predominant_degree_desc'] == 'Bachelors')]



UNITID     OPEID  OPEID6  \
institution_name                                                               
Anderson University                                 150066    178500    1785   
Ball State University                               150136    178600    1786   
Bethel College-Indiana                              150145    178700    1787   
Butler University                                   150163    178800    1788   
Calumet College of Saint Joseph                     150172    183400    1834   
Chamberlain College of Nursing-Indiana              475741    638510    6385   
DePauw University                                   150400    179200    1792   
DeVry University-Indiana                            482486   1072747   10727   
Earlham College                                     150455    179300    1793   
Franklin College                                    150604    179800    1798   
Goshen College                                      150668    179900    1799   
Grace College and Theological Seminary              150677    180000    1800   
Hanover College                                     150756    180100    1801   
Holy Cross College                                  150774    726300    7263   
Huntington University                               150941    180300    1803   
Indiana Institute of Technology                     151290    180500    1805   
Indiana State University                            151324    180700    1807   
Indiana University-Bloomington                      151351    180900    1809   
Indiana University-East                             151388    181100    1811   
Indiana University-Kokomo                           151333    181400    1814   
Indiana University-Northwest                        151360    181500    1815   
Indiana University-Purdue University-Fort Wayne     151102    182800    1828   
Indiana University-Purdue University-Indianapolis   151111    181300    1813   
Indiana University-South Bend                       151342    181600    1816   
Indiana University-Southeast                        151379    181700    1817   
Indiana Wesleyan University-Marion                  151801    182200    1822   
Manchester University                               151777    182000    1820   
Marian University                                   151786    182100    1821   
Martin University                                   151810   2140800   21408   
Oakland City University                             152099    182400    1824   
Ottawa University-Jeffersonville                    442897    193712    1937   
Purdue University-Calumet Campus                    152248    182700    1827   
Purdue University-Main Campus                       243780    182500    1825   
Purdue University-North Central Campus              152266    182600    1826   
Rose-Hulman Institute of Technology                 152318    183000    1830   
Saint Josephs College                               152363    183300    1833   
Saint Mary-of-the-Woods College                     152381    183500    1835   
Saint Mary's College                                152390    183600    1836   
Taylor University                                   152530    183800    1838   
The Art Institute of Indianapolis                   448345   4051304   40513   
Trine University                                    152567    183900    1839   
Trine University-Regional/Non-Traditional Campuses  414878    183901    1839   
University of Evansville                            150534    179500    1795   
University of Indianapolis                          151263    180400    1804   
University of Notre Dame                            152080    184000    1840   
University of Phoenix-Indiana                       443544  32098858   20988   
University of Saint Francis-Fort Wayne              152336    183200    1832   
University of Southern Indiana                      151306    180800    1808   
Valparaiso University                               

### Selecting Multiple Columns of DataFrame

In [52]:
two_columns = college_scorecard[ ['state', 'predominant_degree_desc'] ]
two_columns.head()

state predominant_degree_desc
institution_name                                                    
Alaska Bible College                      AK               Bachelors
Alaska Career College                     AK             Certificate
Alaska Christian College                  AK             Certificate
Alaska Pacific University                 AK               Bachelors
AVTEC-Alaska's Institute of Technology    AK             Certificate

**NOTE**: Among the two sets of square brackets `[[ ]]`, the first set is used to select the columns, the second set is used to list the columns you want to select. 

## Activity On Football Athletes Data

1. Details of the players who are in the freshmen class?
1. Details of the players whose position is offensive linemen (OL) and are in their their last year? 
1. Average height of players whose position is Linebacker (LB) and are Sophmores? 

In [74]:
athletes_data['Class'].unique()
athletes_data['Position'].unique()
athletes_data[ athletes_data['Class'] ==  'Fr.']
athletes_data[ (athletes_data['Position'] == 'OL') & ( (athletes_data['Class'] == 'Sr.') | (athletes_data['Class'] == '5th') ) ]

athletes_data[ 
    (athletes_data['Class'] == 'Soph.') & 
    (athletes_data['Position'] == 'LB')
    ]['Height'].mean()

Number                Name Position  Height  Weight Class  \
3         3    Houston Griffith        S      72     205   Fr.   
5         4        Kevin Austin       WR      74     197   Fr.   
9         7        Derrik Allen        S      73     213   Fr.   
17       12          D.J. Brown       CB      72     191   Fr.   
18       13       Lawrence Keys       WR      70     170   Fr.   
19       13          Paul Moala        S      71     212   Fr.   
22       15       Phil Jurkovec       QB      76     220   Fr.   
24       16         Noah Boykin       CB      73     178   Fr.   
27       18     Joe Wilkins Jr.    WR/DB      73     185   Fr.   
30       19    Justin Ademilola       DE      74     246   Fr.   
31       20  C'Borius Flemister       RB      71     196   Fr.   
36       24       Tommy Tremble       TE      75     228   Fr.   
38       25        Braden Lenzy       WR      71     170   Fr.   
40       26         Leo Albano*       WR      74     205   Fr.   
45       29        Ovie Oghoufo      Rov      75     223   Fr.   
46       29        Matt Salerno       WR      72     185   Fr.   
48       30       Jake Rittman*        P      75     190   Fr.   
49       31           Jack Lamb       LB      76     226   Fr.   
50       31         Cole Capen*       QB      77     220   Fr.   
52       33        Shayne Simon      Rov      75     222   Fr.   
54       34        Jahmir Smith       RB      71     205   Fr.   
55       35         TaRiq Bracy       CB      70     170   Fr.   
65       43      Marcus Thorne*        S      74     200   Fr.   
66       43        Greg Malley*       WR      73     190   Fr.   
76       52            Bo Bauer       LB      75     225   Fr.   
82       55   Jarrett Patterson       OL      76     290   Fr.   
83       56        John Dirksen       OL      77     303   Fr.   
85       57    Jayson Ademilola       DT      75     284   Fr.   
86       60          Cole Mabry       OL      77     270   Fr.   
89       63      Cody Benjamin*       OL      75     230   Fr.   
90       64         Max Siegel*       OL      73     306   Fr.   
91       65     Michael Vinson*       LS      74     228   Fr.   
93       70          Luke Jones       OL      77     303   Fr.   
100      80         Micah Jones       WR      76     212   Fr.   
105      85       George Takacs       TE      78     250   Fr.   
114      98    Ja'Mion Franklin       DT      73     306   Fr.   

                                  Hometown  
3             Chicago, IL/IMG Academy (FL)  
5    Ft. Lauderdale, FL/North Broward Prep  
9                    Marietta, GA/Lassiter  
17      Crownsville, MD/St. John's College  
18             New Orleans, LA/McDonogh 35  
19                      Mishawaka, IN/Penn  
22            Pittsburgh, PA/Pine-Richland  
24                  Washington, DC/Woodson  
27                  North Ft. Myers, FL/HS  
30            Jackson, NJ/St. Peter's Prep  
31              Williamson, GA/Pike County  
36                Johns Creek, GA/Wesleyan  
38                           Tigard, OR/HS  
40           Charleston, SC/Bishop England  
45            Lathrup Village, MI/Harrison  
46                       Encino, CA/Crespi  
48                 Lawrence, KS/Free State  
49                  Temecula, CA/Great Oak  
50                     Orange, CA/Lutheran  
52        West Orange, NJ/St. Peter's Prep  
54                  Sanford, NC/Lee County  
55                         Milpitas, CA/HS  
65                Washington, IN/Community  
66                           Hudson, OH/HS  
76          Harborcreek, PA/Eric Cathedral  
82          Laguna Hills, CA/Mission Viejo  
83            Maria Stein, OH/Marion Local  
85            Jackson, NJ/St. Peter's Prep  
86                        Brentwood, TN/HS  
89               Tampa, Fla./Berkeley Prep  
90    Indianapolis, IN/Brebeuf Jesuit Prep  
91                  Winnetka, IL/New Trier  
93         Little Rock, AR/Pulaski Academy  
100             Gurnee, IL/Warre

## UFunc Arithmatic with Index Preservation

Let us convert the height of the players into meters. The math to convert from inches to meters is to multiply by 0.0254. 

In [75]:
athletes_data.head(5)

Number                  Name Position  Height  Weight  Class  \
0       2       Dexter Williams       RB      71     215    Sr.   
1       2  Jordan Genmark Heath       LB      73     225  Soph.   
2       3           Avery Davis       QB      71     204  Soph.   
3       3      Houston Griffith        S      72     205    Fr.   
4       4          Te'von Coney       LB      73     240    Sr.   

                           Hometown  
0           Orlando, FL/West Orange  
1  San Diego, CA/Cathedral Catholic  
2                 Cedar Hill, TX/HS  
3      Chicago, IL/IMG Academy (FL)  
4         Palm Beach Gardens, FL/HS

In [76]:
athletes_data['Height'] = athletes_data['Height'] * 0.0254

In [77]:
athletes_data.head(5)

Number                  Name Position  Height  Weight  Class  \
0       2       Dexter Williams       RB  1.8034     215    Sr.   
1       2  Jordan Genmark Heath       LB  1.8542     225  Soph.   
2       3           Avery Davis       QB  1.8034     204  Soph.   
3       3      Houston Griffith        S  1.8288     205    Fr.   
4       4          Te'von Coney       LB  1.8542     240    Sr.   

                           Hometown  
0           Orlando, FL/West Orange  
1  San Diego, CA/Cathedral Catholic  
2                 Cedar Hill, TX/HS  
3      Chicago, IL/IMG Academy (FL)  
4         Palm Beach Gardens, FL/HS


Do you see how my index was still preserved? This is referred to as **index preservation** and we will see it come into play both for `Series` and `DataFrame` objects when we using arithmetic functions on them.

## Binary Functions and `DataFrame` Objects
Now let's try performing binary UFunc operations on DataFrames.

#### Operations between 2 DataFrames

To demonstate how arithmetic operations work between two different `DataFrame` objects I'll need to construct a couple of simple objects.

I'll go ahead and create two imaginary objects that hold sales data over two different years for the burger joint: **In-N-Out**

In [78]:
import pandas as pd

# 2015 Sales DataFrame
sales_2015 = pd.DataFrame([
        {'Burgers': 9574265, 'Fries': 7124736, 'Drinks': 11563762},
        {'Burgers': 6574265, 'Fries': 5124736, 'Drinks': 13563762},
    ], 
    index=['California', 'Texas'])

# 2016 Sales DataFrame
# They open their first Indiana store at Notre Dame!!!
# And they sell Irish Shakes nationwide to celebrate.
sales_2016 = pd.DataFrame([
        {'Burgers': 9742652, 'Fries': 7354736, 'Drinks': 11133762, 'Irish Shakes': 75812},
        {'Burgers': 7774222, 'Fries': 6214736, 'Drinks': 14563762, 'Irish Shakes': 15525},
        {'Burgers': 74265, 'Fries': 54736, 'Drinks': 43762, 'Irish Shakes': 23612},
    ], 
    index=['California', 'Texas', 'Indiana'])


Here's what those `DataFrames` look like separately:

In [79]:
print(sales_2015, sales_2016, sep='\n\n\n')

            Burgers    Fries    Drinks
California  9574265  7124736  11563762
Texas       6574265  5124736  13563762


            Burgers    Fries    Drinks  Irish Shakes
California  9742652  7354736  11133762         75812
Texas       7774222  6214736  14563762         15525
Indiana       74265    54736     43762         23612


In [80]:
sales_2015 + sales_2016

Burgers      Drinks       Fries  Irish Shakes
California  19316917.0  22697524.0  14479472.0           NaN
Indiana            NaN         NaN         NaN           NaN
Texas       14348487.0  28127524.0  11339472.0           NaN

To have a value in the results of an operation between two `DataFrame` objects, there must be a value in both of the objects for a given Index/Column combination.

This is why there is no data for Indiana in our results (that index only existed in 2016) and no results for Irish Shakes (that column only existed in 2016).

## Loading JSON Files
In terms of web APIs, JSON is the dominant data transmission format on the internet right now - so you'll need to be familar with how to load it into **`DataFrame`** objects as well.

There are a wide variety of ways that JSON documents can be structured. Unless you want to really start getting down into the,  there are really only a few formats that Pandas will read without problems.

For our purposes, we'll use a pretty basic file that conforms to one of the standard formats just to get our feet wet.

I've uploaded a JSON formatted file `pokedex.json` for us to use.  Hopefully, you are a Pokemon fan.

In [81]:
# We use the `orient` parameter to tell Pandas what the basic 
# structure of the JSON is.  The other options are:
# split, index, columns, and values
# More Info: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_json.html
pokedex = pd.read_json('./data/pokedex.json', orient='records')
pokedex.head()

id  num        name                                               img  \
0   1    1   Bulbasaur  http://www.serebii.net/pokemongo/pokemon/001.png   
1   2    2     Ivysaur  http://www.serebii.net/pokemongo/pokemon/002.png   
2   3    3    Venusaur  http://www.serebii.net/pokemongo/pokemon/003.png   
3   4    4  Charmander  http://www.serebii.net/pokemongo/pokemon/004.png   
4   5    5  Charmeleon  http://www.serebii.net/pokemongo/pokemon/005.png   

              type  height    weight             candy  candy_count  \
0  [Grass, Poison]  0.71 m    6.9 kg   Bulbasaur Candy         25.0   
1  [Grass, Poison]  0.99 m   13.0 kg   Bulbasaur Candy        100.0   
2  [Grass, Poison]  2.01 m  100.0 kg   Bulbasaur Candy          NaN   
3           [Fire]  0.61 m    8.5 kg  Charmander Candy         25.0   
4           [Fire]  1.09 m   19.0 kg  Charmander Candy        100.0   

           egg  spawn_chance  avg_spawns spawn_time multipliers  \
0         2 km         0.690        69.0      20:00      [1.58]   
1  Not in Eggs         0.042         4.2      07:00  [1.2, 1.6]   
2  Not in Eggs         0.017         1.7      11:30        None   
3         2 km         0.253        25.3      08:45      [1.65]   
4  Not in Eggs         0.012         1.2      19:00      [1.79]   

                     weaknesses  \
0  [Fire, Ice, Flying, Psychic]   
1  [Fire, Ice, Flying, Psychic]   
2  [Fire, Ice, Flying, Psychic]   
3         [Water, Ground, Rock]   
4         [Water, Ground, Rock]   

                                      next_evolution  \
0  [{'num': '002', 'name': 'Ivysaur'}, {'num': '0...   
1               [{'num': '003', 'name': 'Venusaur'}]   
2                                                NaN   
3  [{'num': '005', 'name': 'Charmeleon'}, {'num':...   
4              [{'num': '006', 'name': 'Charizard'}]   

                                      prev_evolution  
0                                                NaN  
1              [{'num': '001', 'name': 'Bulbasaur'}]  
2  [{'num': '001', 'name': 'Bulbasaur'}, {'num': ...  
3                                                NaN  
4             [{'num': '004', 'name': 'Charmander'}]

## Practice Dictionary Activity

1. Accept a string as an input from the user
2. Create a dictionary that contains the frequency of each word in the string.
3. Print the dictionary

Below is the sample interaction

In [85]:
# Accept a setence
sentence = input("Enter a sentence")
# Convert the sentence to a list of words using split() function
words_list = sentence.split()
# Create an empty dictionary that contains words and frequencies
words = {}

# Iterate through every word in the list
for word in words_list:
    if word not in words:
        words[word] = 1
    else:
        words[word] += 1
# Finally print the dictionary
print(words)

Enter a sentenceMy name is My name is My name is Jonathan
{'My': 3, 'name': 3, 'is': 3, 'Jonathan': 1}
