# Variable Assignments and Data Types

In [1]:
name = "Jonathan"
birth_month = 3
print(birth_month)
birth_month = "March"
print(birth_month)

3
March


## Fancy Print and Input Statements

In [2]:
print(name, birth_month)
print(name + " was born in " + birth_month)
print("{} was born in {}".format(name, birth_month))

# who would you specifiy the order on insertions
# what about formatting numbers? IE. If you want to round to 2 decimel points?

Jonathan March
Jonathan was born in March
Jonathan was born in March


In [3]:
print("what is your name? ")
your_name = input()
print("what is your birth month? ")
your_birth_month = input()
print("{} was born in {}".format(your_name, your_birth_month))

what is your name? 
jon
what is your birth month? 
3/23
jon was born in 3/23


In [ ]:
your_name = input("What is your name? ")
your_birth_month = input("What month were you born in? ")
print("{} was born in {}".format(your_name, your_birth_month))

## Converting between Data Types

In [4]:
my_var = "42"
print("{} is a {}".format(my_var, type(my_var)))

my_var = 42
print("{} is a {}".format(my_var, type(my_var)))

my_var = 4.2
print("{} is a {}".format(my_var, type(my_var)))

my_float_as_str = str(my_var)
print("{} is a {}".format(my_float_as_str, type(my_float_as_str)))

my_float_as_str_and_back_again_but_then_an_integer = int(float(my_float_as_str))
print("{} is a {}".format(my_float_as_str_and_back_again_but_then_an_integer, type(my_float_as_str_and_back_again_but_then_an_integer)))

# my_float_as_str_and_back_again_but_then_an_integer is a bad variable name...

42 is a <class 'str'>
42 is a <class 'int'>
4.2 is a <class 'float'>
4.2 is a <class 'str'>
4 is a <class 'int'>


In [5]:
# what's going on here?

num1 = input("Give me a number... ")
num2 = input("Give me another number... ")

print("result: ", num1 + num2)
print("result: ", num1 * num2)

Give me a number... 3
Give me another number... 4
result:  34


TypeError: can't multiply sequence by non-int of type 'str'

# Flow Control with Conditionals and Boolean Operators

In [6]:
num = int(input("Give me a number... "))

if num % 2 == 0:
    print("Your number is even")

Give me a number... 2
Your number is even


In [7]:
num = int(input("Give me a number... "))

if num % 2 == 0:
    print("Your number is even")
else: 
    print("your number is odd")

Give me a number... 3
your number is odd


In [8]:
price = 2.50
#Step 1: Accept the inputs
amount = int(input("How many pounds do you want? "))
money = int(input("How much money you got? "))

total_cost = amount * price
diff = money - total_cost

print("total cost: ",total_cost)
print("diff: ", diff)
#Step 2: Calculate the change
#Step 3: Conditional statement to print the output  

if diff > 0:
    print("Sure thing buddy. Where is your {:.2f} in change".format(diff))
elif diff < 0:
    print("Uh oh. You still need {:.2f} monies".format(diff * -1))
else:
    print("WOW. Exact change!")


How many pounds do you want? 100
How much money you got? 10000
total cost:  250.0
diff:  9750.0
Sure thing buddy. Where is your 9750.00 in change


In [9]:
# Conditional logic can become more complicated
year = int(input("Give me a year. "))

if (year % 4 == 0) and (year % 100 != 0):
    print("yep. leap year")
else:
    print("Nope. boring year")
    if year % 2 == 0:
        print("But at least it's even!")


Give me a year. 2000
Nope. boring year
But at least it's even!


When using operators like `and` and `or` in a conditional statement... what are the other options?

How are the different that what you use (later) with array like objects in numpy?

# Loops

## for loops

In [10]:
print("a sequence of numbers")
for el in range(10):
    print(el)

print("a sequence of odd numbers")
for i in range(16):
    if i % 2 == 1:
        print(i)    
    
print("also a sequence of odd numbers")
for i in range(1,16,2):
    print(i)

a sequence of numbers
0
1
2
3
4
5
6
7
8
9
a sequence of odd numbers
1
3
5
7
9
11
13
15
also a sequence of odd numbers
1
3
5
7
9
11
13
15


## while loops

In [11]:
print("print numbers until the value is greater than 10")
i = 0
while(i<10):
    print(str(i) + " is not greater than 10")
    i = i + 1


print numbers until the value is greater than 10
0 is not greater than 10
1 is not greater than 10
2 is not greater than 10
3 is not greater than 10
4 is not greater than 10
5 is not greater than 10
6 is not greater than 10
7 is not greater than 10
8 is not greater than 10
9 is not greater than 10


In [12]:
# understand how this works and what 'break' means on ln 16
# Go back an review/practice the version of this (Presidents) with the three hints

answer = "Parasite"
is_correct = False
counter = 0
while not is_correct:
    guess = input("What movie won the 2020 Best Picture at the Oscars? ")
    counter  = counter + 1
    if guess == answer:
        is_correct = True
        print("Correct!!!")
    else:
        print("Nope. Guess again")
        
        if counter > 5:
            print("Sorry. Out of guesses")
            break

What movie won the 2020 Best Picture at the Oscars? asdf
Nope. Guess again
What movie won the 2020 Best Picture at the Oscars? Parasite
Correct!!!


# Functions

In [13]:
def repeater(arg):
    # notice what happens when you multiply a string
    return str(arg) * 5

repeater(5)

'55555'

In [14]:
def repeater(word, count=5):
    return str(word) * count

repeater("woof")

'woofwoofwoofwoofwoof'

In [16]:
# What's different here? What will it return?
def repeater(word, count=5):
   print(str(word) * count)

result = repeater("woof ",10)

print(result)

woof woof woof woof woof woof woof woof woof woof 
None


## Scopes: Private vs. Global

In [17]:
def private_example(arg):
    private_var = "secret"
    return arg * 4

something = private_example('foobar')
print(something)
print(private_var)

# What are the rules for private and public variables?
# how does it affect lists that are assigned by reference?

foobarfoobarfoobarfoobar


NameError: name 'private_var' is not defined

# Lists

In [20]:
# python lists are heterogeneous. they can contain anything
list1 = [1,2.0,3,None,False,"word", [1,2,3]]
print(list1)

# access lists via index
print("first item is index 0: {}".format(  list1[0]  ))
print("last item is index -1: {}".format(  list1[-1]  ))
print("slice the list using ':' : {}".format(  list1[2:5]  ))
print("slice the list using '::-2' : {}".format(  list1[::-2]  ))


[1, 2.0, 3, None, False, 'word', [1, 2, 3]]
first item is index 0: 1
last item is index -1: [1, 2, 3]
slice the list using ':' : [3, None, False]
slice the list using '::-2' : [[1, 2, 3], False, 3, 1]


In [18]:
# Assignment by reference

var_1 = "foobar"

print("var 1 is: {}".format(var_1))
var_2 = var_1

var_2 = "bazz"
print("var 1 is now: {}".format(var_1))
print("var 2 is: {}".format(var_2))

list2 = [1,2,3]
print("list 2 is: {}".format(list2))
list3 = list2

list3[0] = 100

print("list 2 is now: {}".format(list2))

# if you want to make ana actual copy of a list, how do you do that?

var 1 is: foobar
var 1 is now: foobar
var 2 is: bazz
list 2 is: [1, 2, 3]
list 2 is now: [100, 2, 3]


In [21]:
# use for loops to loop through lists
print("\nfor loop backwards")
for i in list1[::-1]:
    print(i, type(i))
    
# But you could use a while loop using a counter and len() to get the number of items in the list
print("\nwhile loop")
i = 0
while i < len(list1):
    item_at_index = list1[i]
    print(item_at_index, type(item_at_index))
    i = i + 1



for loop backwards
[1, 2, 3] <class 'list'>
word <class 'str'>
False <class 'bool'>
None <class 'NoneType'>
3 <class 'int'>
2.0 <class 'float'>
1 <class 'int'>

while loop
1 <class 'int'>
2.0 <class 'float'>
3 <class 'int'>
None <class 'NoneType'>
False <class 'bool'>
word <class 'str'>
[1, 2, 3] <class 'list'>


In [22]:
print("Python".lower())
words = []

# Accept 5 words
for i in range(3):
    word = input("Best programming languages... ")
    words.append(word.lower())

# check if value is in list
if "python" in words:
    print("Nice to include Python!")
else:
    print(":-(")

python
Best programming languages... ruby
Best programming languages... java
Best programming languages... c
:-(


In [23]:
# What is list comprehension?
schools = ['Notre Dame', 'Michigan', 'Brown', 'Chicago']
["Trash" if s == 'Michigan' else s for s in schools]

['Notre Dame', 'Trash', 'Brown', 'Chicago']

In [24]:
# you can do fun things with lists
list_of_strs = ['one', 'two', 'three']
list_of_nums = [1,2,3,4]
print(list_of_nums * 5)
print(list_of_strs * 5)
# print(list_of_nums * list_of_strs)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
['one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three']


In [ ]:
# what are max() min()... functions used for?
# what's the difference between append() and insert()

# What place in data analytics do lists have? 
# what are some some things python lists can do that arrays can't?
    # When and where should you use them or not use them?

# Fixed Type Arrays

In [25]:
import array

basic_list = list(range(10))
print(basic_list)

# designate type as integer
basic_array = array.array('i',basic_list)
print(basic_array)

# designate type as float
basic_f_array = array.array('f',basic_list)
print(basic_f_array)

# what similarities do lists and arrays have? Differences?

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])


# Importing Modules

In [2]:
# we imported array which is part of basic python, just not loaded automatically
# but we also use 3rd party modules that also need to be loaded using import
# what does `as` do?

import numpy as np
import pandas as pd

# NumPy - Numerical Python

In [ ]:
list_of_ints = [0, 1, 2, 3, 4, 5]
list_to_np = np.array(list_of_ints)
print(list_to_np)
print(type(list_to_np))


# How do you create np arrays from scratch?

In [27]:
np_array = np.array(range(10))
np_range = np.arange(10)


print(np_range[0])
print(np_range[-1])
print(np_range[2:7])
print(np_range[7:2:-1])

# seems a lot like lists...

0
9
[2 3 4 5 6]
[7 6 5 4 3]


In [28]:
# 2 dimensional arrays FTW!
two_dimensional_array = np.array([range(i, i + 3) for i in [2, 4, 6]])
two_dimensional_array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [29]:
print("Get the 0th indexed row (only specify an \"x\" coordinate)")
print(two_dimensional_array[0])

print("Get the 3nd indexed (index 2) row")
print(two_dimensional_array[2])

print("Get 2nd indexed row and then get the 2nd indexed (1) column  in that row. ")
print(two_dimensional_array[2][1])

print('Go through each array and collect the first element in each')
print(two_dimensional_array[:3,0])

print('Go through each array starting at index 1 and up to but not includeing 3 and return the first of those arrays')
print(two_dimensional_array[1:3][0])

print('Go through each array and return a slice containing the first of those arrays')
print(two_dimensional_array[:,:1])

Get the 0th indexed row (only specify an "x" coordinate)
[2 3 4]
Get the 3nd indexed (index 2) row
[6 7 8]
Get 2nd indexed row and then get the 2nd indexed (1) column  in that row. 
7
Go through each array and collect the first element in each
[2 4 6]
Go through each array starting at index 1 and up to but not includeing 3 and return the first of those arrays
[4 5 6]
Go through each array and return a slice containing the first of those arrays
[[2]
 [4]
 [6]]


In [ ]:
# Numpy Attributes

#     ndim
#     shape
#     size
#     dtype
#     itemsize
#     nbytes

In [30]:
# sort an array

new_array = np.array([2,5,1,89,3,0])
print(new_array)
print(np.sort(new_array))
print(new_array)

# sorting is not remembered? How are two ways you could make it 'stick'?

[ 2  5  1 89  3  0]
[ 0  1  2  3  5 89]
[ 2  5  1 89  3  0]


In [ ]:
# How would you split numpy arrays?

## Univeral Functions (UFuncts)

In [31]:
# don't use loops or list type operations on np arrays. Use universal functions
# why ^^
np_array = np.array(range(5))

print(np_array ** 2)
print(np_array / 2)
print(np_array % 2)
print(np.sum(np_array))

# what is the other syntax to accomplish this?
# what are the other arithmetic ufuncts available? What do they do?

[ 0  1  4  9 16]
[0.  0.5 1.  1.5 2. ]
[0 1 0 1 0]
10


In [32]:
arr_1 = np.arange(1, 6)
arr_2 = np.arange(6, 11)

print(arr_1 + arr_2)
print(arr_1 / arr_2)

[ 7  9 11 13 15]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [33]:
print("2 dim: \n", two_dimensional_array)
arr_3 = np.array([1,2,3])
print("new array: \n",arr_3)

print("multipy: \n", two_dimensional_array * arr_3)
print("add: \n", two_dimensional_array + arr_3)

2 dim: 
 [[2 3 4]
 [4 5 6]
 [6 7 8]]
new array: 
 [1 2 3]
multipy: 
 [[ 2  6 12]
 [ 4 10 18]
 [ 6 14 24]]
add: 
 [[ 3  5  7]
 [ 5  7  9]
 [ 7  9 11]]


In [34]:
# why doesn't this work

arr_4 = np.array([1,2])
print(arr_4)

two_dimensional_array * arr_4

[1 2]


ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [35]:
# but then why does this work?
arr_5 = [[1],[5],[10]]
arr_6 = [1,5,10]
print("array: \n",two_dimensional_array)
print("array 5: \n",arr_5)
print("array + 5: \n",two_dimensional_array + arr_5)
print("array 6: \n",arr_5)
print("array + 6: \n",two_dimensional_array + arr_6)

array: 
 [[2 3 4]
 [4 5 6]
 [6 7 8]]
array 5: 
 [[1], [5], [10]]
array + 5: 
 [[ 3  4  5]
 [ 9 10 11]
 [16 17 18]]
array 6: 
 [[1], [5], [10]]
array + 6: 
 [[ 3  8 14]
 [ 5 10 16]
 [ 7 12 18]]


## Aggregation

In [36]:
# what are the aggregation functions available?

np_array_2 = np.array([1,45,99,1000000])

print(np.mean(np_array_2))
print(np.median(np_array_2))
print(np.sum(np_array_2))

250036.25
72.0
1000145


## Masking

In [37]:
# What is masking?

array_of_nums = np.arange(100)
array_of_nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
array_of_nums % 3 == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True])

In [39]:
# what is going on in each of these? What are the other bitwise operators?
# how do they line up with the regular operators in python?

div_by_3 = array_of_nums % 3 == 0
print("there are {} numbers in the list that are divisible by 3".format(div_by_3.sum()))

div_by_3_and_2 = (array_of_nums % 3 == 0) & (array_of_nums % 2 == 0)
print("there are {} numbers in the list that are divisible by 3 and 2".format(div_by_3_and_2.sum()))

div_by_3_or_7 = (array_of_nums % 3 == 0) | (array_of_nums % 7 == 0)
print("there are {} numbers in the list that are divisible by 3 or 7".format(div_by_3_or_7.sum()))

there are 34 numbers in the list that are divisible by 3
there are 17 numbers in the list that are divisible by 3 and 2
there are 44 numbers in the list that are divisible by 3 or 7


# Dictionaries

In [40]:
# basic dictionary

person = {
    "name": "Jonathan",
    "age": "24",
    "honestly_level": 0,
    "pets": ["Chi Chi the Chinchilla", "Buckley", "Sebastian"],
    "Good Teacher": False
}
print(person)

jonathan = person
jonathan['age'] = "32"
jonathan['honestly_level'] = 3
jonathan["misc"] = "foo bar bazz"

print(person)

for pet in person["pets"]:
    print(pet)

{'name': 'Jonathan', 'age': '24', 'honestly_level': 0, 'pets': ['Chi Chi the Chinchilla', 'Buckley', 'Sebastian'], 'Good Teacher': False}
{'name': 'Jonathan', 'age': '32', 'honestly_level': 3, 'pets': ['Chi Chi the Chinchilla', 'Buckley', 'Sebastian'], 'Good Teacher': False, 'misc': 'foo bar bazz'}
Chi Chi the Chinchilla
Buckley
Sebastian


In [ ]:
# hey hey hey hey na na na goodbye
sent = input("Enter a sentence: ")

# Convert the sentence to a list of words using split() function
words_list = sent.split()

# Create an empty dictionary that contains words and frequencies
word_counts = {}
# Iterate through every word in the list
for w in words_list:
    if w in word_counts:
        word_counts[w] = word_counts[w] + 1
    else:
        word_counts[w] = 1

print(word_counts)


# Pandas

## Loading and Viewing Data

In [44]:
# this is loading a JSON file. 
# How do we load CSV files? How so you write a dataframe to file?
pokedex = pd.read_json('./data/pokedex.json')
pokedex.head()

id  num        name                                               img  \
0   1    1   Bulbasaur  http://www.serebii.net/pokemongo/pokemon/001.png   
1   2    2     Ivysaur  http://www.serebii.net/pokemongo/pokemon/002.png   
2   3    3    Venusaur  http://www.serebii.net/pokemongo/pokemon/003.png   
3   4    4  Charmander  http://www.serebii.net/pokemongo/pokemon/004.png   
4   5    5  Charmeleon  http://www.serebii.net/pokemongo/pokemon/005.png   

              type  height    weight             candy  candy_count  \
0  [Grass, Poison]  0.71 m    6.9 kg   Bulbasaur Candy         25.0   
1  [Grass, Poison]  0.99 m   13.0 kg   Bulbasaur Candy        100.0   
2  [Grass, Poison]  2.01 m  100.0 kg   Bulbasaur Candy          NaN   
3           [Fire]  0.61 m    8.5 kg  Charmander Candy         25.0   
4           [Fire]  1.09 m   19.0 kg  Charmander Candy        100.0   

           egg  spawn_chance  avg_spawns spawn_time multipliers  \
0         2 km         0.690        69.0      20:00      [1.58]   
1  Not in Eggs         0.042         4.2      07:00  [1.2, 1.6]   
2  Not in Eggs         0.017         1.7      11:30        None   
3         2 km         0.253        25.3      08:45      [1.65]   
4  Not in Eggs         0.012         1.2      19:00      [1.79]   

                     weaknesses  \
0  [Fire, Ice, Flying, Psychic]   
1  [Fire, Ice, Flying, Psychic]   
2  [Fire, Ice, Flying, Psychic]   
3         [Water, Ground, Rock]   
4         [Water, Ground, Rock]   

                                      next_evolution  \
0  [{'num': '002', 'name': 'Ivysaur'}, {'num': '0...   
1               [{'num': '003', 'name': 'Venusaur'}]   
2                                                NaN   
3  [{'num': '005', 'name': 'Charmeleon'}, {'num':...   
4              [{'num': '006', 'name': 'Charizard'}]   

                                      prev_evolution  
0                                                NaN  
1              [{'num': '001', 'name': 'Bulbasaur'}]  
2  [{'num': '001', 'name': 'Bulbasaur'}, {'num': ...  
3                                                NaN  
4             [{'num': '004', 'name': 'Charmander'}]

## Dataframes and Series

In [42]:
# dataframe consists of columns and rows
print(type(pokedex))
# columns act like a key from a dictionary and the value is the series (think numpy array)
name_series = pokedex['name']
print(type(name_series))
print(pokedex.keys())

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
Index(['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy',
       'candy_count', 'egg', 'spawn_chance', 'avg_spawns', 'spawn_time',
       'multipliers', 'weaknesses', 'next_evolution', 'prev_evolution'],
      dtype='object')


In [46]:
# a dataframe as an index (0-based by default)
print(pokedex.index)

# but you can set it to something else (even strings)
pokedex.set_index('name', inplace=True)
print(pokedex.index)
pokedex.head()

# What are two other ways to set the index of a dataframe?

RangeIndex(start=0, stop=151, step=1)
Index(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon',
       'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie',
       ...
       'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dratini',
       'Dragonair', 'Dragonite', 'Mewtwo', 'Mew'],
      dtype='object', name='name', length=151)


id  num                                               img  \
name                                                                    
Bulbasaur    1    1  http://www.serebii.net/pokemongo/pokemon/001.png   
Ivysaur      2    2  http://www.serebii.net/pokemongo/pokemon/002.png   
Venusaur     3    3  http://www.serebii.net/pokemongo/pokemon/003.png   
Charmander   4    4  http://www.serebii.net/pokemongo/pokemon/004.png   
Charmeleon   5    5  http://www.serebii.net/pokemongo/pokemon/005.png   

                       type  height    weight             candy  candy_count  \
name                                                                           
Bulbasaur   [Grass, Poison]  0.71 m    6.9 kg   Bulbasaur Candy         25.0   
Ivysaur     [Grass, Poison]  0.99 m   13.0 kg   Bulbasaur Candy        100.0   
Venusaur    [Grass, Poison]  2.01 m  100.0 kg   Bulbasaur Candy          NaN   
Charmander           [Fire]  0.61 m    8.5 kg  Charmander Candy         25.0   
Charmeleon           [Fire]  1.09 m   19.0 kg  Charmander Candy        100.0   

                    egg  spawn_chance  avg_spawns spawn_time multipliers  \
name                                                                       
Bulbasaur          2 km         0.690        69.0      20:00      [1.58]   
Ivysaur     Not in Eggs         0.042         4.2      07:00  [1.2, 1.6]   
Venusaur    Not in Eggs         0.017         1.7      11:30        None   
Charmander         2 km         0.253        25.3      08:45      [1.65]   
Charmeleon  Not in Eggs         0.012         1.2      19:00      [1.79]   

                              weaknesses  \
name                                       
Bulbasaur   [Fire, Ice, Flying, Psychic]   
Ivysaur     [Fire, Ice, Flying, Psychic]   
Venusaur    [Fire, Ice, Flying, Psychic]   
Charmander         [Water, Ground, Rock]   
Charmeleon         [Water, Ground, Rock]   

                                               next_evolution  \
name                                                            
Bulbasaur   [{'num': '002', 'name': 'Ivysaur'}, {'num': '0...   
Ivysaur                  [{'num': '003', 'name': 'Venusaur'}]   
Venusaur                                                  NaN   
Charmander  [{'num': '005', 'name': 'Charmeleon'}, {'num':...   
Charmeleon              [{'num': '006', 'name': 'Charizard'}]   

                                               prev_evolution  
name                                                           
Bulbasaur                                                 NaN  
Ivysaur                 [{'num': '001', 'name': 'Bulbasaur'}]  
Venusaur    [{'num': '001', 'name': 'Bulbasaur'}, {'num': ...  
Charmander                                                NaN  
Charmeleon             [{'num': '004', 'name': 'Charmander'}]

## Indexing and Selection


In [47]:
# What does inplace=True do? What's another way to accomplish the same thing?
pokedex.sort_index(inplace=True)
pokedex.head(3)

id  num                                               img  \
name                                                                     
Abra         63   63  http://www.serebii.net/pokemongo/pokemon/063.png   
Aerodactyl  142  142  http://www.serebii.net/pokemongo/pokemon/142.png   
Alakazam     65   65  http://www.serebii.net/pokemongo/pokemon/065.png   

                      type  height   weight       candy  candy_count  \
name                                                                   
Abra             [Psychic]  0.89 m  19.5 kg  Abra Candy         25.0   
Aerodactyl  [Rock, Flying]  1.80 m  59.0 kg        None          NaN   
Alakazam         [Psychic]  1.50 m  48.0 kg  Abra Candy          NaN   

                    egg  spawn_chance  avg_spawns spawn_time  \
name                                                           
Abra               5 km        0.4200       42.00      04:30   
Aerodactyl        10 km        0.0180        1.80      23:40   
Alakazam    Not in Eggs        0.0073        0.73      12:33   

                                         multipliers  \
name                                                   
Abra        [1.3599999999999999, 1.9500000000000002]   
Aerodactyl                                      None   
Alakazam                                        None   

                                     weaknesses  \
name                                              
Abra                         [Bug, Ghost, Dark]   
Aerodactyl  [Water, Electric, Ice, Rock, Steel]   
Alakazam                     [Bug, Ghost, Dark]   

                                               next_evolution  \
name                                                            
Abra        [{'num': '064', 'name': 'Kadabra'}, {'num': '0...   
Aerodactyl                                                NaN   
Alakazam                                                  NaN   

                                               prev_evolution  
name                                                           
Abra                                                      NaN  
Aerodactyl                                                NaN  
Alakazam    [{'num': '063', 'name': 'Abra'}, {'num': '064'...

In [48]:
# Select a series (limit to first 5)
pokedex['egg'][:5]

name
Abra                 5 km
Aerodactyl          10 km
Alakazam      Not in Eggs
Arbok         Not in Eggs
Arcanine      Not in Eggs
Name: egg, dtype: object

In [49]:
# Select a single series but within a dataframe. 
pokedex[['egg']][:5]

egg
name                   
Abra               5 km
Aerodactyl        10 km
Alakazam    Not in Eggs
Arbok       Not in Eggs
Arcanine    Not in Eggs

In [50]:
# Select multiple series (limit to first 5) -- Notice that we use a list here
pokedex[ ['height', 'weight'] ][:5]

height    weight
name                        
Abra        0.89 m   19.5 kg
Aerodactyl  1.80 m   59.0 kg
Alakazam    1.50 m   48.0 kg
Arbok       3.51 m   65.0 kg
Arcanine    1.91 m  155.0 kg

In [51]:
# slice by index
# how does this differ from slicing by index in a list or array? Can you still use 0-based index?
pokedex['Ponyta':'Psyduck']

id  num                                               img  \
name                                                                   
Ponyta     77   77  http://www.serebii.net/pokemongo/pokemon/077.png   
Porygon   137  137  http://www.serebii.net/pokemongo/pokemon/137.png   
Primeape   57   57  http://www.serebii.net/pokemongo/pokemon/057.png   
Psyduck    54   54  http://www.serebii.net/pokemongo/pokemon/054.png   

                type  height   weight          candy  candy_count  \
name                                                                
Ponyta        [Fire]  0.99 m  30.0 kg   Ponyta Candy         50.0   
Porygon     [Normal]  0.79 m  36.5 kg           None          NaN   
Primeape  [Fighting]  0.99 m  32.0 kg   Mankey Candy          NaN   
Psyduck      [Water]  0.79 m  19.6 kg  Psyduck Candy         50.0   

                  egg  spawn_chance  avg_spawns spawn_time  multipliers  \
name                                                                      
Ponyta           5 km         0.510        51.0      02:50  [1.48, 1.5]   
Porygon          5 km         0.012         1.2      02:49         None   
Primeape  Not in Eggs         0.031         3.1      12:33         None   
Psyduck          5 km         2.540       254.0      03:41       [2.27]   

                        weaknesses                        next_evolution  \
name                                                                       
Ponyta       [Water, Ground, Rock]  [{'num': '078', 'name': 'Rapidash'}]   
Porygon                 [Fighting]                                   NaN   
Primeape  [Flying, Psychic, Fairy]                                   NaN   
Psyduck          [Electric, Grass]   [{'num': '055', 'name': 'Golduck'}]   

                              prev_evolution  
name                                          
Ponyta                                   NaN  
Porygon                                  NaN  
Primeape  [{'num': '056', 'name': 'Mankey'}]  
Psyduck                                  NaN

In [52]:
# get a specific row using .loc[]
# what is .iloc[]
print(type(pokedex.loc['Eevee']))
print(pokedex.loc['Eevee'].index)
pokedex.loc['Eevee']

<class 'pandas.core.series.Series'>
Index(['id', 'num', 'img', 'type', 'height', 'weight', 'candy', 'candy_count',
       'egg', 'spawn_chance', 'avg_spawns', 'spawn_time', 'multipliers',
       'weaknesses', 'next_evolution', 'prev_evolution'],
      dtype='object')


id                                                              133
num                                                             133
img                http://www.serebii.net/pokemongo/pokemon/133.png
type                                                       [Normal]
height                                                       0.30 m
weight                                                       6.5 kg
candy                                                   Eevee Candy
candy_count                                                      25
egg                                                           10 km
spawn_chance                                                   2.75
avg_spawns                                                      275
spawn_time                                                    05:32
multipliers                                            [2.02, 2.64]
weaknesses                                               [Fighting]
next_evolution    [{'num': '134', 'name': 'Vapor

In [53]:
# More list/array/dictionary like functions

print("Justin Bieber" in pokedex.index)
print("Eevee" in pokedex.index)

False
True


## Masking

In [54]:
# what does this do?
pokedex['spawn_chance'] > .5

name
Abra          False
Aerodactyl    False
Alakazam      False
Arbok         False
Arcanine      False
              ...  
Weepinbell    False
Weezing       False
Wigglytuff    False
Zapdos        False
Zubat          True
Name: spawn_chance, Length: 151, dtype: bool

In [55]:
(pokedex['spawn_chance'] < .5) & (pokedex['avg_spawns'] < 30)

name
Abra          False
Aerodactyl     True
Alakazam       True
Arbok          True
Arcanine       True
              ...  
Weepinbell     True
Weezing        True
Wigglytuff     True
Zapdos         True
Zubat         False
Length: 151, dtype: bool

In [56]:
# use the mask on a dataframe
pokedex[ (pokedex['spawn_chance'] < .5) & (pokedex['avg_spawns'] > 30) ].sample(5)

id  num                                               img  \
name                                                                    
Abra        63   63  http://www.serebii.net/pokemongo/pokemon/063.png   
Diglett     50   50  http://www.serebii.net/pokemongo/pokemon/050.png   
Jigglypuff  39   39  http://www.serebii.net/pokemongo/pokemon/039.png   
Machop      66   66  http://www.serebii.net/pokemongo/pokemon/066.png   
Raticate    20   20  http://www.serebii.net/pokemongo/pokemon/020.png   

                  type  height   weight             candy  candy_count  \
name                                                                     
Abra         [Psychic]  0.89 m  19.5 kg        Abra Candy         25.0   
Diglett       [Ground]  0.20 m   0.8 kg     Diglett Candy         50.0   
Jigglypuff    [Normal]  0.51 m   5.5 kg  Jigglypuff Candy         50.0   
Machop      [Fighting]  0.79 m  19.5 kg      Machop Candy         25.0   
Raticate      [Normal]  0.71 m  18.5 kg     Rattata Candy          NaN   

                    egg  spawn_chance  avg_spawns spawn_time  \
name                                                           
Abra               5 km          0.42        42.0      04:30   
Diglett            5 km          0.40        40.0      02:22   
Jigglypuff         2 km          0.39        39.0      08:46   
Machop             5 km          0.49        49.0      01:55   
Raticate    Not in Eggs          0.41        41.0      01:56   

                                         multipliers  \
name                                                   
Abra        [1.3599999999999999, 1.9500000000000002]   
Diglett                                       [2.69]   
Jigglypuff                                    [1.85]   
Machop                    [1.6400000000000001, 1.65]   
Raticate                                        None   

                          weaknesses  \
name                                   
Abra              [Bug, Ghost, Dark]   
Diglett          [Water, Grass, Ice]   
Jigglypuff                [Fighting]   
Machop      [Flying, Psychic, Fairy]   
Raticate                  [Fighting]   

                                               next_evolution  \
name                                                            
Abra        [{'num': '064', 'name': 'Kadabra'}, {'num': '0...   
Diglett                   [{'num': '051', 'name': 'Dugtrio'}]   
Jigglypuff             [{'num': '040', 'name': 'Wigglytuff'}]   
Machop      [{'num': '067', 'name': 'Machoke'}, {'num': '0...   
Raticate                                                  NaN   

                                 prev_evolution  
name                                             
Abra                                        NaN  
Diglett                                     NaN  
Jigglypuff                                  NaN  
Machop                                      NaN  
Raticate    [{'num': '019', 'name': 'Rattata'}]

## Missing Data

In [57]:
# how many rows with candy count are missing?
# where have we seen something like this before?

pokedex['candy_count'].isnull().sum()

81

In [58]:
# understand why the shape for each of these is different
print(pokedex.shape)
print(pokedex.dropna().shape)
print(pokedex.dropna(thresh=15).shape)
print(pokedex.dropna(axis=1).shape)

(151, 16)
(16, 16)
(70, 16)
(151, 12)


In [59]:
# get the null count for the entire dataframe
print(pokedex[['num','candy','next_evolution','prev_evolution']].isnull()[:5])

              num  candy  next_evolution  prev_evolution
name                                                    
Abra        False  False           False            True
Aerodactyl  False  False            True            True
Alakazam    False  False            True           False
Arbok       False  False            True           False
Arcanine    False  False            True           False


In [60]:
print(pokedex.isnull().sum())

id                 0
num                0
img                0
type               0
height             0
weight             0
candy              0
candy_count       81
egg                0
spawn_chance       0
avg_spawns         0
spawn_time         0
multipliers       81
weaknesses         0
next_evolution    81
prev_evolution    79
dtype: int64


In [61]:
print( pokedex.isnull().mean()* 100 )

id                 0.000000
num                0.000000
img                0.000000
type               0.000000
height             0.000000
weight             0.000000
candy              0.000000
candy_count       53.642384
egg                0.000000
spawn_chance       0.000000
avg_spawns         0.000000
spawn_time         0.000000
multipliers       53.642384
weaknesses         0.000000
next_evolution    53.642384
prev_evolution    52.317881
dtype: float64


In [ ]:
pokedex['candy_count']

In [62]:
# what is we want to populate the missing numbers with '0'. in this case that makes sense
print(pokedex['candy_count'].fillna(0)[:5])
# but it does not save it
print(pokedex['candy_count'][:5])
poke_with_zeros = pokedex['candy_count'].fillna(0)
poke_with_zeros

name
Abra          25.0
Aerodactyl     0.0
Alakazam       0.0
Arbok          0.0
Arcanine       0.0
Name: candy_count, dtype: float64
name
Abra          25.0
Aerodactyl     NaN
Alakazam       NaN
Arbok          NaN
Arcanine       NaN
Name: candy_count, dtype: float64


name
Abra           25.0
Aerodactyl      0.0
Alakazam        0.0
Arbok           0.0
Arcanine        0.0
              ...  
Weepinbell    100.0
Weezing         0.0
Wigglytuff      0.0
Zapdos          0.0
Zubat          50.0
Name: candy_count, Length: 151, dtype: float64

In [63]:
pokedex['candy_count'].fillna(0, inplace=True)
pokedex.head()

id  num                                               img  \
name                                                                     
Abra         63   63  http://www.serebii.net/pokemongo/pokemon/063.png   
Aerodactyl  142  142  http://www.serebii.net/pokemongo/pokemon/142.png   
Alakazam     65   65  http://www.serebii.net/pokemongo/pokemon/065.png   
Arbok        24   24  http://www.serebii.net/pokemongo/pokemon/024.png   
Arcanine     59   59  http://www.serebii.net/pokemongo/pokemon/059.png   

                      type  height    weight            candy  candy_count  \
name                                                                         
Abra             [Psychic]  0.89 m   19.5 kg       Abra Candy         25.0   
Aerodactyl  [Rock, Flying]  1.80 m   59.0 kg             None          0.0   
Alakazam         [Psychic]  1.50 m   48.0 kg       Abra Candy          0.0   
Arbok             [Poison]  3.51 m   65.0 kg      Ekans Candy          0.0   
Arcanine            [Fire]  1.91 m  155.0 kg  Growlithe Candy          0.0   

                    egg  spawn_chance  avg_spawns spawn_time  \
name                                                           
Abra               5 km        0.4200       42.00      04:30   
Aerodactyl        10 km        0.0180        1.80      23:40   
Alakazam    Not in Eggs        0.0073        0.73      12:33   
Arbok       Not in Eggs        0.0720        7.20      01:50   
Arcanine    Not in Eggs        0.0170        1.70      03:11   

                                         multipliers  \
name                                                   
Abra        [1.3599999999999999, 1.9500000000000002]   
Aerodactyl                                      None   
Alakazam                                        None   
Arbok                                           None   
Arcanine                                        None   

                                     weaknesses  \
name                                              
Abra                         [Bug, Ghost, Dark]   
Aerodactyl  [Water, Electric, Ice, Rock, Steel]   
Alakazam                     [Bug, Ghost, Dark]   
Arbok                         [Ground, Psychic]   
Arcanine                  [Water, Ground, Rock]   

                                               next_evolution  \
name                                                            
Abra        [{'num': '064', 'name': 'Kadabra'}, {'num': '0...   
Aerodactyl                                                NaN   
Alakazam                                                  NaN   
Arbok                                                     NaN   
Arcanine                                                  NaN   

                                               prev_evolution  
name                                                           
Abra                                                      NaN  
Aerodactyl                                                NaN  
Alakazam    [{'num': '063', 'name': 'Abra'}, {'num': '064'...  
Arbok                       [{'num': '023', 'name': 'Ekans'}]  
Arcanine                [{'num': '058', 'name': 'Growlithe'}]

In [64]:
# if you want to fill the missing numbers with an aggregation, you can also do that 
pokedex = pd.read_json('./data/pokedex.json')
pokedex = pokedex.set_index('name')
pokedex = pokedex.sort_index()
pokedex.head()

id  num                                               img  \
name                                                                     
Abra         63   63  http://www.serebii.net/pokemongo/pokemon/063.png   
Aerodactyl  142  142  http://www.serebii.net/pokemongo/pokemon/142.png   
Alakazam     65   65  http://www.serebii.net/pokemongo/pokemon/065.png   
Arbok        24   24  http://www.serebii.net/pokemongo/pokemon/024.png   
Arcanine     59   59  http://www.serebii.net/pokemongo/pokemon/059.png   

                      type  height    weight            candy  candy_count  \
name                                                                         
Abra             [Psychic]  0.89 m   19.5 kg       Abra Candy         25.0   
Aerodactyl  [Rock, Flying]  1.80 m   59.0 kg             None          NaN   
Alakazam         [Psychic]  1.50 m   48.0 kg       Abra Candy          NaN   
Arbok             [Poison]  3.51 m   65.0 kg      Ekans Candy          NaN   
Arcanine            [Fire]  1.91 m  155.0 kg  Growlithe Candy          NaN   

                    egg  spawn_chance  avg_spawns spawn_time  \
name                                                           
Abra               5 km        0.4200       42.00      04:30   
Aerodactyl        10 km        0.0180        1.80      23:40   
Alakazam    Not in Eggs        0.0073        0.73      12:33   
Arbok       Not in Eggs        0.0720        7.20      01:50   
Arcanine    Not in Eggs        0.0170        1.70      03:11   

                                         multipliers  \
name                                                   
Abra        [1.3599999999999999, 1.9500000000000002]   
Aerodactyl                                      None   
Alakazam                                        None   
Arbok                                           None   
Arcanine                                        None   

                                     weaknesses  \
name                                              
Abra                         [Bug, Ghost, Dark]   
Aerodactyl  [Water, Electric, Ice, Rock, Steel]   
Alakazam                     [Bug, Ghost, Dark]   
Arbok                         [Ground, Psychic]   
Arcanine                  [Water, Ground, Rock]   

                                               next_evolution  \
name                                                            
Abra        [{'num': '064', 'name': 'Kadabra'}, {'num': '0...   
Aerodactyl                                                NaN   
Alakazam                                                  NaN   
Arbok                                                     NaN   
Arcanine                                                  NaN   

                                               prev_evolution  
name                                                           
Abra                                                      NaN  
Aerodactyl                                                NaN  
Alakazam    [{'num': '063', 'name': 'Abra'}, {'num': '064'...  
Arbok                       [{'num': '023', 'name': 'Ekans'}]  
Arcanine                [{'num': '058', 'name': 'Growlithe'}]

In [65]:
pokedex['candy_count'].mean()
pokedex['candy_count'].fillna( pokedex['candy_count'].mean() , inplace=True)
pokedex.head()

id  num                                               img  \
name                                                                     
Abra         63   63  http://www.serebii.net/pokemongo/pokemon/063.png   
Aerodactyl  142  142  http://www.serebii.net/pokemongo/pokemon/142.png   
Alakazam     65   65  http://www.serebii.net/pokemongo/pokemon/065.png   
Arbok        24   24  http://www.serebii.net/pokemongo/pokemon/024.png   
Arcanine     59   59  http://www.serebii.net/pokemongo/pokemon/059.png   

                      type  height    weight            candy  candy_count  \
name                                                                         
Abra             [Psychic]  0.89 m   19.5 kg       Abra Candy         25.0   
Aerodactyl  [Rock, Flying]  1.80 m   59.0 kg             None         57.3   
Alakazam         [Psychic]  1.50 m   48.0 kg       Abra Candy         57.3   
Arbok             [Poison]  3.51 m   65.0 kg      Ekans Candy         57.3   
Arcanine            [Fire]  1.91 m  155.0 kg  Growlithe Candy         57.3   

                    egg  spawn_chance  avg_spawns spawn_time  \
name                                                           
Abra               5 km        0.4200       42.00      04:30   
Aerodactyl        10 km        0.0180        1.80      23:40   
Alakazam    Not in Eggs        0.0073        0.73      12:33   
Arbok       Not in Eggs        0.0720        7.20      01:50   
Arcanine    Not in Eggs        0.0170        1.70      03:11   

                                         multipliers  \
name                                                   
Abra        [1.3599999999999999, 1.9500000000000002]   
Aerodactyl                                      None   
Alakazam                                        None   
Arbok                                           None   
Arcanine                                        None   

                                     weaknesses  \
name                                              
Abra                         [Bug, Ghost, Dark]   
Aerodactyl  [Water, Electric, Ice, Rock, Steel]   
Alakazam                     [Bug, Ghost, Dark]   
Arbok                         [Ground, Psychic]   
Arcanine                  [Water, Ground, Rock]   

                                               next_evolution  \
name                                                            
Abra        [{'num': '064', 'name': 'Kadabra'}, {'num': '0...   
Aerodactyl                                                NaN   
Alakazam                                                  NaN   
Arbok                                                     NaN   
Arcanine                                                  NaN   

                                               prev_evolution  
name                                                           
Abra                                                      NaN  
Aerodactyl                                                NaN  
Alakazam    [{'num': '063', 'name': 'Abra'}, {'num': '064'...  
Arbok                       [{'num': '023', 'name': 'Ekans'}]  
Arcanine                [{'num': '058', 'name': 'Growlithe'}]

## Combining Pandas Datasets

### Concatenation

In [ ]:
poke_1 = pokedex.iloc[:25]
poke_2 = pokedex.iloc[25:100]
poke_3 = pokedex.iloc[100:]
print(poke_1.shape, poke_2.shape,poke_3.shape)

In [ ]:
new_poke_df = pd.concat([poke_3, poke_2, poke_1])
print(new_poke_df.shape)
print(poke_1.shape[0] + poke_2.shape[0] + poke_3.shape[0])
new_poke_df.head()

# what does verify_integrity do?
# what does ignore_index do?
# is there a way to tell is there are duplicates?

### Merging

In [66]:
pop = pd.read_csv('./data/state-population.csv')
areas = pd.read_csv('./data/state-areas.csv')
abbrevs = pd.read_csv('./data/state-abbrevs.csv')

In [67]:
# you can see that these two dfs share a common column, 'state' but the last does not
# this makes merging easy

print(areas.sample())
print(abbrevs.sample())
print(pop.sample())

    state  area (sq. mi)
18  Maine          35387
        state abbreviation
49  Wisconsin           WI
     state_abrv   ages  year  population
2464         PR  total  1997         NaN


In [68]:
left_merged_df = pd.merge(abbrevs, areas)

In [69]:
# why does this break?
pd.merge(left_merged_df, pop)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [70]:
# sometimes you have to explain to pandas how dataframes relate to each other
pd.merge(left_merged_df, pop, left_on="abbreviation", right_on="state_abrv")

state abbreviation  area (sq. mi) state_abrv     ages  year  \
0     Alabama           AL          52423         AL  under18  2012   
1     Alabama           AL          52423         AL    total  2012   
2     Alabama           AL          52423         AL  under18  2010   
3     Alabama           AL          52423         AL    total  2010   
4     Alabama           AL          52423         AL  under18  2011   
...       ...          ...            ...        ...      ...   ...   
2443  Wyoming           WY          97818         WY  under18  1993   
2444  Wyoming           WY          97818         WY    total  1991   
2445  Wyoming           WY          97818         WY  under18  1991   
2446  Wyoming           WY          97818         WY  under18  1990   
2447  Wyoming           WY          97818         WY    total  1990   

      population  
0      1117489.0  
1      4817528.0  
2      1130966.0  
3      4785570.0  
4      1125763.0  
...          ...  
2443    137458.0  
2444    459260.0  
2445    136720.0  
2446    136078.0  
2447    453690.0  

[2448 rows x 7 columns]

In [ ]:
# you need to join not on a column but an index?
# what would you do with this? 
# can it be done?

abbres_with_index = abbrevs.set_index('abbreviation')
abbres_with_index.head()
# now do the join...

## Different Type of Joins

In [5]:
# Team Members Favorite Restaurants
team_restaurants = pd.DataFrame(
    {'restaurant': ['In-N-Out', 'Chipotle', 'Chick-Fil-A'], 
    'name': ['Mike', 'Kim', 'Roger']})

# Restaurant Items
restaurant_items = pd.DataFrame(
    {
        'item': [
        'Shakes', 
        'Burritos', 
        'Burger'
        ]
    ,
        'restaurant':[
        'In-N-Out',
        'Chipotle',
        'Five Guys',
    ]
    }
)


In [6]:
team_restaurants

restaurant   name
0     In-N-Out   Mike
1     Chipotle    Kim
2  Chick-Fil-A  Roger

In [73]:
restaurant_items

item restaurant
0    Shakes   In-N-Out
1  Burritos   Chipotle
2    Burger  Five Guys

In [7]:
pd.merge(team_restaurants, restaurant_items, how="inner") # default

restaurant  name      item
0   In-N-Out  Mike    Shakes
1   Chipotle   Kim  Burritos

In [8]:
pd.merge(team_restaurants, restaurant_items, how="outer")

restaurant   name      item
0     In-N-Out   Mike    Shakes
1     Chipotle    Kim  Burritos
2  Chick-Fil-A  Roger       NaN
3    Five Guys    NaN    Burger

In [9]:
pd.merge(team_restaurants, restaurant_items, how="left")

restaurant   name      item
0     In-N-Out   Mike    Shakes
1     Chipotle    Kim  Burritos
2  Chick-Fil-A  Roger       NaN

In [10]:
pd.merge(team_restaurants, restaurant_items, how="right")

restaurant  name      item
0   In-N-Out  Mike    Shakes
1   Chipotle   Kim  Burritos
2  Five Guys   NaN    Burger